import type { Anomaly } from '@/domain/anomaly';

/**
 * Banco de Anomalias do Dia (Etapa 7): 5 por ilha de começo; a Etapa 15 sobe para 12 por ilha
 * (15A: Lógica e Banco de Dados). Cada uma tem uma frase de história do Eco e um desafio de até
 * ~3 minutos. O sorteio do dia está em domain/anomaly. Para
 * acrescentar, é só pôr mais uma aqui (id novo, nunca reaproveitado).
 * Gerado e conferido: as saídas de PHP/SQL e os blocos try rodam nos testes de conteúdo;
 * Python e Java estão em docs/engajamento/conferir-output.md.
 */
export const anomalies: Anomaly[] = [
  {
    id: 'logica-portao-aberto',
    era: 'logica',
    title: 'O portão abre para qualquer senha',
    story: 'O Eco trocou um sinal na conferência da senha e agora qualquer um entra no farol.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'O portão abre até com a senha errada. Toque na linha com o bug.',
      lines: [
        '<?php',
        '$senha = "1234";',
        'if ($senha = "0000") {',
        '    echo "Portão aberto";',
        '}',
      ],
      bugLine: 3,
      explain:
        'Um <code>=</code> guarda o valor; comparar é <code>==</code>. Com um só, a condição vira verdadeira e o portão sempre abre.',
    },
  },
  {
    id: 'logica-laco-eterno',
    era: 'logica',
    title: 'Um laço que nunca termina',
    story: 'O Eco virou a contagem ao contrário e o farol ficou preso repetindo para sempre.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'Este laço deveria contar de 1 a 3. Toque na linha com o bug.',
      lines: ['<?php', 'for ($i = 1; $i <= 3; $i--) {', '    echo $i;', '}'],
      bugLine: 2,
      explain:
        '<code>$i--</code> faz o contador descer, e <code>$i &lt;= 3</code> nunca fica falso. O certo é <code>$i++</code>.',
    },
  },
  {
    id: 'logica-soma-texto',
    era: 'logica',
    title: 'Um número disfarçado de texto',
    story: 'O Eco guardou o 5 entre aspas para confundir a conta. Descubra o que o PHP mostra.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\n$a = "5";\n$b = 3;\necho $a + $b;',
      options: ['8', '53', 'Erro', '5'],
      answer: 0,
      explain:
        'O <code>+</code> soma números: o PHP converte o texto "5" em número e mostra 8. Para juntar textos seria o ponto (<code>.</code>).',
    },
  },
  {
    id: 'logica-saudacao-sumiu',
    era: 'logica',
    title: 'A saudação do farol sumiu',
    story: 'O Eco desmontou a linha que cumprimenta os viajantes. Monte de novo.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte a linha que mostra a saudação em PHP',
      pieces: ['echo', '"Olá, viajante"', ';'],
      distractors: ['print(', 'console.log'],
      explain:
        'Em PHP quem mostra texto na tela é o <code>echo</code>, e todo comando termina com ponto e vírgula.',
    },
  },
  {
    id: 'logica-dobro',
    era: 'logica',
    title: 'O cálculo do dobro parou de aparecer',
    story: 'O Eco apagou a última linha do programa. Faça o PHP mostrar o dobro de 21 de novo.',
    level: 'Base',
    challenge: {
      t: 'try',
      engine: 'php',
      brief: 'Mostre na tela o dobro de $n',
      starter: '<?php\n$n = 21;\n',
      hint: 'Use echo e multiplique: echo $n * 2;',
      file: 'dobro.php',
      solution: '<?php\n$n = 21;\necho $n * 2;',
    },
  },
  {
    id: 'logica-par-impar',
    era: 'logica',
    title: 'O farol não sabe se o número é par',
    story: 'O Eco apagou a placa que separava pares e ímpares. Descubra o que o programa mostra.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\n$n = 7;\necho $n % 2 == 0 ? "par" : "ímpar";',
      options: ['ímpar', 'par', '1', '7'],
      answer: 0,
      explain: 'O <code>%</code> dá o resto da divisão: 7 dividido por 2 sobra 1, então não é par.',
    },
  },
  {
    id: 'logica-maior-idade',
    era: 'logica',
    title: 'Quem tem 18 anos não entra',
    story: 'O Eco trocou um sinal e barrou justamente quem acabou de fazer 18 anos.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'Quem tem exatamente 18 anos não consegue entrar. Toque na linha com o bug.',
      lines: ['<?php', '$idade = 18;', 'if ($idade > 18) {', '    echo "Pode entrar";', '}'],
      bugLine: 3,
      explain: '<code>&gt;</code> deixa o 18 de fora. Para incluir, é <code>&gt;=</code> (maior ou igual).',
    },
  },
  {
    id: 'logica-contagem-regressiva',
    era: 'logica',
    title: 'A contagem para o salto quebrou',
    story: 'O Eco embaralhou o laço da contagem regressiva do salto no tempo. Monte de novo: 3, 2, 1.',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte o começo do laço que conta 3, 2, 1',
      pieces: ['for (', '$i = 3;', '$i >= 1;', '$i--', ')'],
      distractors: ['$i++', '$i <= 1;'],
      explain: 'Começa em 3, continua enquanto for maior ou igual a 1, e desce um por vez com <code>$i--</code>.',
    },
  },
  {
    id: 'logica-soma-notas',
    era: 'logica',
    title: 'O boletim ficou sem a soma',
    story: 'O Eco sumiu com o laço que somava as notas. Faça o PHP mostrar a soma de novo.',
    level: 'Intermediário',
    challenge: {
      t: 'try',
      engine: 'php',
      brief: 'Some as notas do array e mostre o total',
      starter: '<?php\n$notas = [7, 8, 9];\n$soma = 0;\n',
      hint: 'Use foreach ($notas as $nota) { $soma += $nota; } e depois echo $soma;',
      file: 'notas.php',
      solution: '<?php\n$notas = [7, 8, 9];\n$soma = 0;\nforeach ($notas as $nota) {\n    $soma += $nota;\n}\necho $soma;',
    },
  },
  {
    id: 'logica-funcao-dobro',
    era: 'logica',
    title: 'A função que não devolve nada',
    story: 'O Eco arrancou a palavra que faz a função entregar o resultado.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      q: 'Complete para a função devolver o dobro:',
      fill: true,
      pre: 'function dobro($x) {\n   ',
      post: '$x * 2;\n}',
      accept: ['return'],
      wrong: ['echo', 'print', 'break'],
      placeholder: '?',
      explain: '<code>return</code> devolve o valor para quem chamou a função. <code>echo</code> só mostraria na tela.',
    },
  },
  {
    id: 'logica-guarda-chuva',
    era: 'logica',
    title: 'A previsão do tempo enlouqueceu',
    story: 'O Eco misturou os operadores lógicos da previsão. Descubra o que ela diz de verdade.',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\n$chuva = true;\n$guardaChuva = false;\nif ($chuva && !$guardaChuva) {\n    echo "molhou";\n} else {\n    echo "seco";\n}',
      options: ['molhou', 'seco', 'true', 'nada'],
      answer: 0,
      explain: 'Está chovendo (<code>true</code>) e <code>!false</code> é <code>true</code>: as duas partes do <code>&amp;&amp;</code> são verdadeiras.',
    },
  },
  {
    id: 'logica-lista-eras',
    era: 'logica',
    title: 'A lista de eras perdeu a ordem',
    story: 'O Eco jura que a segunda era da lista é a primeira. Mostre quem está certo.',
    level: 'Avançado',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\n$eras = ["Dados", "Lógica", "Git"];\necho count($eras) . " " . $eras[1];',
      options: ['3 Lógica', '3 Dados', '2 Lógica', '3 Git'],
      answer: 0,
      explain: 'O array tem 3 itens, e as posições começam em 0: <code>$eras[1]</code> é o segundo, "Lógica".',
    },
  },
  {
    id: 'bd-sem-estoque',
    era: 'banco-de-dados',
    title: 'Um SELECT está trazendo produtos sem estoque',
    story: 'O Eco mexeu no filtro. Conserte a consulta antes que a linha ramifique.',
    level: 'Base',
    challenge: {
      t: 'try',
      engine: 'sql',
      brief: 'Mostre só os produtos que têm estoque',
      starter: 'SELECT nome, estoque\nFROM produtos;',
      hint: 'Falta o filtro: WHERE estoque > 0 (antes do ponto e vírgula).',
      file: 'loja.sql',
      ds: 'loja',
      solution: 'SELECT nome, estoque FROM produtos WHERE estoque > 0;',
    },
  },
  {
    id: 'bd-email-nulo',
    era: 'banco-de-dados',
    title: 'Os clientes sem e-mail sumiram do relatório',
    story: 'O Eco comparou com NULL do jeito errado e a consulta nunca encontra ninguém.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'Esta consulta deveria achar os clientes sem e-mail. Toque na linha com o bug.',
      lines: ['SELECT nome', 'FROM clientes', 'WHERE email = NULL;'],
      bugLine: 3,
      explain: 'NULL só se testa com <code>IS NULL</code>. <code>= NULL</code> nunca é verdadeiro.',
    },
  },
  {
    id: 'bd-pedidos-grandes',
    era: 'banco-de-dados',
    title: 'O relatório de vendas foi embaralhado',
    story: 'O Eco misturou os números das vendas. Leia a consulta e descubra o resultado real.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'Os pedidos da loja são de 250,00, 80,00 e 129,90. O que aparece?',
      lang: 'sql',
      code: 'SELECT COUNT(*) FROM pedidos\nWHERE total > 100;',
      options: ['2', '3', '1', '0'],
      answer: 0,
      explain: 'Só 250,00 e 129,90 passam de 100: são 2 pedidos.',
    },
  },
  {
    id: 'bd-mais-caro-primeiro',
    era: 'banco-de-dados',
    title: 'A vitrine ficou de cabeça para baixo',
    story: 'O Eco inverteu a ordem da vitrine: os produtos baratos aparecem primeiro.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte o fim da consulta para mostrar do mais caro ao mais barato',
      pieces: ['ORDER BY', 'preco', 'DESC'],
      distractors: ['ASC', 'SORT'],
      explain:
        '<code>ORDER BY preco DESC</code> ordena do maior para o menor. ASC (o padrão) faria o contrário.',
    },
  },
  {
    id: 'bd-join-sem-on',
    era: 'banco-de-dados',
    title: 'Pedidos sem dono',
    story:
      'O Eco cortou a ligação entre clientes e pedidos. Complete o JOIN para cada pedido achar seu cliente.',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      q: 'Complete a ligação entre as tabelas:',
      fill: true,
      pre: 'SELECT c.nome, p.total\nFROM clientes c\nJOIN pedidos p',
      post: 'p.cliente_id = c.id;',
      accept: ['ON'],
      wrong: ['WHERE', 'AS', 'IN'],
      placeholder: '?',
      explain:
        'O <code>ON</code> diz como as linhas das duas tabelas se casam: pela chave estrangeira cliente_id.',
    },
  },
  {
    id: 'bd-media-precos',
    era: 'banco-de-dados',
    title: 'O preço médio da vitrine sumiu',
    story: 'O Eco apagou o relatório do preço médio. Leia a consulta e descubra o valor.',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'Os produtos custam 249,90, 129,90, 899,00 e 179,90. O que aparece?',
      lang: 'sql',
      code: 'SELECT ROUND(AVG(preco), 2) FROM produtos;',
      options: ['364.68', '364.67', '1458.70', '4'],
      answer: 0,
      explain: 'A soma é 1458,70; dividida por 4 dá 364,675, e o <code>ROUND(..., 2)</code> arredonda para 364,68.',
    },
  },
  {
    id: 'bd-cliente-sem-pedido',
    era: 'banco-de-dados',
    title: 'Uma cliente sumiu das vendas',
    story: 'O Eco escondeu quem ainda não comprou nada. Encontre essa pessoa antes que ela suma de vez.',
    level: 'Avançado',
    challenge: {
      t: 'try',
      engine: 'sql',
      brief: 'Mostre o nome dos clientes que nunca fizeram um pedido',
      starter: 'SELECT nome\nFROM clientes;',
      hint: 'Filtre com WHERE id NOT IN (SELECT cliente_id FROM pedidos), ou use um LEFT JOIN.',
      file: 'loja.sql',
      ds: 'loja',
      solution: 'SELECT nome FROM clientes WHERE id NOT IN (SELECT cliente_id FROM pedidos);',
    },
  },
  {
    id: 'bd-reajuste-geral',
    era: 'banco-de-dados',
    title: 'O reajuste pegou a loja inteira',
    story: 'Era para aumentar só os teclados, mas o Eco tirou uma parte do comando e todo produto ficou mais caro.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'O aumento devia valer só para os teclados (categoria 1), mas mudou todos os produtos. Toque na linha com o bug.',
      lines: ['UPDATE produtos', 'SET preco = preco * 1.1;'],
      bugLine: 2,
      explain: 'Faltou o filtro antes do ponto e vírgula: <code>WHERE categoria_id = 1</code>. Sem WHERE, o UPDATE muda todas as linhas.',
    },
  },
  {
    id: 'bd-produtos-por-categoria',
    era: 'banco-de-dados',
    title: 'A contagem por categoria foi desmontada',
    story: 'O Eco espalhou as peças da consulta que conta os produtos de cada categoria.',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte a consulta que conta os produtos de cada categoria',
      pieces: ['SELECT categoria_id, COUNT(*)', 'FROM produtos', 'GROUP BY categoria_id'],
      distractors: ['ORDER BY COUNT', 'WHERE COUNT(*) > 1'],
      explain: 'O <code>GROUP BY</code> junta as linhas de cada categoria, e o <code>COUNT(*)</code> conta quantas há em cada grupo.',
    },
  },
  {
    id: 'bd-busca-teclado',
    era: 'banco-de-dados',
    title: 'A busca por teclados parou de achar',
    story: 'O Eco trocou o operador da busca e agora só aparece o que tem o nome exato.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      q: 'Complete para achar todo produto que começa com "Teclado":',
      fill: true,
      pre: 'SELECT nome FROM produtos\nWHERE nome',
      post: "'Teclado%';",
      accept: ['LIKE'],
      wrong: ['=', 'IN', 'BETWEEN'],
      placeholder: '?',
      explain: 'O <code>LIKE</code> compara com um padrão: o <code>%</code> vale qualquer coisa depois de "Teclado".',
    },
  },
  {
    id: 'bd-total-da-ana',
    era: 'banco-de-dados',
    title: 'Quanto a Ana já gastou?',
    story: 'O Eco apagou o total de compras da cliente número 1. Descubra quanto era.',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'A cliente 1 (Ana) fez os pedidos de 250,00 e 80,00; o cliente 2 fez um de 129,90. O que aparece?',
      lang: 'sql',
      code: 'SELECT SUM(total) FROM pedidos\nWHERE cliente_id = 1;',
      options: ['330.00', '250.00', '459.90', '2'],
      answer: 0,
      explain: 'O <code>WHERE</code> deixa só os pedidos da Ana, e o <code>SUM</code> soma: 250,00 + 80,00 = 330,00.',
    },
  },
  {
    id: 'bd-apagar-um-pedido',
    era: 'banco-de-dados',
    title: 'Um pedido cancelado continua na lista',
    story: 'O pedido 102 foi cancelado, mas o Eco quer apagar a tabela inteira junto. Escolha o comando certo.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      q: 'Qual comando apaga só o pedido 102?',
      options: ['DELETE FROM pedidos WHERE id = 102;', 'DELETE FROM pedidos;', 'DROP TABLE pedidos;', 'DELETE pedidos 102;'],
      answer: 0,
      explain: 'Com <code>WHERE id = 102</code>, só aquela linha sai. Sem WHERE, o DELETE apaga todas; o DROP apaga a tabela inteira.',
    },
  },
  {
    id: 'py-print-solto',
    era: 'python',
    title: 'Um print escapou do laço',
    story: 'O Eco empurrou uma linha para fora do lugar e o Python recusa rodar o programa.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'Este código dá IndentationError. Toque na linha com o bug.',
      lines: ['for i in range(3):', 'print(i)'],
      bugLine: 2,
      explain:
        'Em Python o bloco do <code>for</code> é marcado pela indentação: o <code>print</code> precisa estar recuado.',
    },
  },
  {
    id: 'py-contagem',
    era: 'python',
    title: 'A contagem começou do lugar errado',
    story:
      'O Eco mexeu no range e ninguém sabe mais onde a contagem começa. Descubra o que aparece.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'python',
      code: 'for i in range(1, 4):\n    print(i, end=" ")',
      options: ['1 2 3', '0 1 2 3', '1 2 3 4', '0 1 2'],
      answer: 0,
      explain: '<code>range(1, 4)</code> começa no 1 e para antes do 4: 1, 2, 3.',
    },
  },
  {
    id: 'py-fstring',
    era: 'python',
    title: 'A mensagem mostra {nome} em vez do nome',
    story: 'O Eco apagou uma letra e o texto parou de trocar a variável pelo valor.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      q: 'Complete para o Python trocar {nome} pelo valor da variável:',
      fill: true,
      pre: 'nome = "Ana"\nprint(',
      post: '"Olá, {nome}")',
      accept: ['f'],
      wrong: ['r', 'b', 'u'],
      placeholder: '?',
      explain:
        'Com <code>f</code> antes das aspas (f-string), o Python troca <code>{nome}</code> pelo valor: "Olá, Ana".',
    },
  },
  {
    id: 'py-mochila',
    era: 'python',
    title: 'Quantos itens tem a mochila?',
    story: 'O Eco colocou mais um item na mochila escondido. Descubra quantos ficaram.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'python',
      code: 'itens = ["mapa", "lanterna"]\nitens.append("bússola")\nprint(len(itens))',
      options: ['2', '3', '1', 'erro'],
      answer: 1,
      explain:
        '<code>append</code> põe um item no fim da lista: agora são 3, e <code>len</code> conta.',
    },
  },
  {
    id: 'py-funcao',
    era: 'python',
    title: 'A função perdeu o nome',
    story:
      'O Eco apagou a primeira linha da função. Monte de novo para o dobro voltar a funcionar.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte a primeira linha de uma função Python chamada dobro, que recebe n',
      pieces: ['def', 'dobro(n):'],
      distractors: ['function', 'func'],
      explain:
        'Em Python, toda função começa com <code>def</code>, o nome, os parâmetros e dois-pontos.',
    },
  },
  {
    id: 'java-ponto-virgula',
    era: 'java',
    title: 'O compilador parou tudo',
    story: 'O Eco roubou um ponto e vírgula e o programa nem chega a rodar.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'O compilador reclama deste trecho (dentro do main). Toque na linha com o bug.',
      lines: ['int vidas = 3', 'System.out.println(vidas);'],
      bugLine: 1,
      explain: 'Em Java toda instrução termina com ponto e vírgula. Sem ele, erro de compilação.',
    },
  },
  {
    id: 'java-divisao',
    era: 'java',
    title: 'Metade de 7 virou 3',
    story: 'O Eco dividiu dois inteiros e a parte decimal sumiu. Descubra o que aparece.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela (código dentro do main)?',
      lang: 'java',
      code: 'System.out.println(7 / 2);',
      options: ['3.5', '3', '4', 'erro de compilação'],
      answer: 1,
      explain:
        'Divisão entre dois int descarta a parte decimal: 7 / 2 dá 3. Com 7.0 / 2 daria 3.5.',
    },
  },
  {
    id: 'java-senha',
    era: 'java',
    title: 'A senha certa não abre a porta',
    story: 'O Eco comparou dois textos com == e agora nem a senha certa funciona.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      q: 'Complete para comparar o conteúdo das Strings:',
      fill: true,
      pre: 'if (senha.',
      post: '("1234")) {',
      accept: ['equals'],
      wrong: ['compare', 'same', 'is'],
      placeholder: '?',
      explain:
        '<code>equals</code> compara o texto. O <code>==</code> compara se são o mesmo objeto na memória.',
    },
  },
  {
    id: 'java-pares',
    era: 'java',
    title: 'O laço dos números pares',
    story: 'O Eco multiplicou tudo por 2 dentro do laço. Leia e descubra o que aparece.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela (código dentro do main)?',
      lang: 'java',
      code: 'for (int i = 0; i < 3; i++) {\n  System.out.print(i * 2);\n}',
      options: ['024', '246', '0246', '123'],
      answer: 0,
      explain: 'i vale 0, 1 e 2; vezes 2 dá 0, 2 e 4, impressos lado a lado: 024.',
    },
  },
  {
    id: 'java-ola',
    era: 'java',
    title: 'O Olá, Java desapareceu',
    story: 'O Eco desmontou a linha que imprime a mensagem. Monte de novo.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte a linha que imprime Olá, Java',
      pieces: ['System.out.println(', '"Olá, Java"', ');'],
      distractors: ['print(', 'echo'],
      explain:
        'Em Java, <code>System.out.println</code> mostra o texto e pula linha; a instrução termina com ponto e vírgula.',
    },
  },
  {
    id: 'php-saudacao',
    era: 'php',
    title: 'A saudação ficou pela metade',
    story: 'O Eco quebrou a junção dos textos. Leia e descubra o que o PHP mostra.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\n$nome = "Ana";\necho "Olá, " . $nome . "!";',
      options: ['Olá, Ana!', 'Olá, $nome!', 'Olá, !', 'Erro'],
      answer: 0,
      explain: 'O ponto junta textos: "Olá, " + "Ana" + "!".',
    },
  },
  {
    id: 'php-malabarismo',
    era: 'php',
    title: 'O golpe do malabarismo de tipos',
    story: 'O Eco aprendeu os truques de Malabari: agora 0 e "0" parecem a mesma coisa. Ou não?',
    level: 'Intermediário',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\nvar_dump(0 === "0");',
      options: ['bool(true)', 'bool(false)', 'NULL', 'Erro'],
      answer: 1,
      explain:
        '<code>===</code> compara valor E tipo: um é int, o outro é string, então é false. Com <code>==</code> daria true.',
    },
  },
  {
    id: 'php-contar',
    era: 'php',
    title: 'Quantos fragmentos sobraram?',
    story: 'O Eco escondeu fragmentos num array. Descubra quantos são.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'output',
      q: 'O que aparece na tela?',
      lang: 'php',
      code: '<?php\n$fragmentos = ["azul", "verde", "roxo"];\necho count($fragmentos);',
      options: ['2', '3', '0', 'Erro'],
      answer: 1,
      explain: '<code>count</code> devolve quantos itens o array tem: 3.',
    },
  },
  {
    id: 'php-cifrao',
    era: 'php',
    title: 'Uma variável sem o cifrão',
    story: 'O Eco roubou um símbolo e o PHP não reconhece mais a variável.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'Este código dá erro. Toque na linha com o bug.',
      lines: ['<?php', '$vidas = 3;', 'echo vidas;'],
      bugLine: 3,
      explain:
        'Toda variável PHP começa com <code>$</code>, também ao usar: <code>echo $vidas;</code>.',
    },
  },
  {
    id: 'php-cracha',
    era: 'php',
    title: 'O crachá do viajante está em branco',
    story: 'O Eco apagou o texto do crachá. Faça o PHP mostrar o nome de novo.',
    level: 'Base',
    challenge: {
      t: 'try',
      engine: 'php',
      brief: 'Mostre "Viajante: Ana" usando a variável $nome',
      starter: '<?php\n$nome = "Ana";\n',
      hint: 'Com aspas duplas a variável vira o valor: echo "Viajante: $nome";',
      file: 'cracha.php',
      solution: '<?php\n$nome = "Ana";\necho "Viajante: $nome";',
    },
  },
  {
    id: 'git-repo-sumiu',
    era: 'git-github',
    title: 'A linha do tempo do projeto sumiu',
    story: 'O Eco apagou o repositório. Recrie a linha do tempo nesta pasta.',
    level: 'Base',
    challenge: {
      t: 'try',
      engine: 'git',
      brief: 'Transforme esta pasta num repositório Git',
      starter: '',
      hint: 'Um comando só: git init',
      file: 'terminal — pasta vazia',
      repo: 'vazio',
      mission: 'm1',
      solution: 'git init',
    },
  },
  {
    id: 'git-commit-em-ordem',
    era: 'git-github',
    title: 'Os passos do commit foram trocados',
    story: 'O Eco embaralhou os comandos do dia a dia. Coloque na ordem certa.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'order',
      q: 'Monte os dois comandos que gravam as mudanças no histórico',
      pieces: ['git add .', 'git commit -m "salva"'],
      distractors: ['git push --force'],
      explain:
        'Primeiro <code>git add</code> prepara (staging area), depois <code>git commit</code> grava.',
    },
  },
  {
    id: 'git-o-que-mudou',
    era: 'git-github',
    title: 'Ninguém sabe o que mudou',
    story: 'O Eco mexeu em arquivos às escondidas. Descubra com um comando o que mudou.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      q: 'Complete o comando que mostra o que mudou e o que está preparado:',
      fill: true,
      pre: 'git',
      post: '',
      accept: ['status'],
      wrong: ['log', 'push', 'init'],
      placeholder: '?',
      explain:
        '<code>git status</code> mostra arquivos modificados, novos e os que estão na staging area.',
    },
  },
  {
    id: 'git-branch-feature',
    era: 'git-github',
    title: 'O recurso novo está na linha errada',
    story: 'O Eco quer que você mexa direto na main. Abra uma linha paralela antes.',
    level: 'Base',
    challenge: {
      t: 'try',
      engine: 'git',
      brief: 'Crie o branch feature e mude para ele',
      starter: 'git init\ngit add .\ngit commit -m "início"\n',
      hint: 'Dois comandos: git branch feature e git switch feature.',
      file: 'terminal — meu-projeto',
      repo: 'projeto',
      mission: 'm3',
      solution:
        'git init\ngit add .\ngit commit -m "início"\ngit branch feature\ngit switch feature',
    },
  },
  {
    id: 'git-letra-trocada',
    era: 'git-github',
    title: 'Um comando com uma letra a menos',
    story: 'O Eco comeu uma letra do comando e o terminal não entende mais.',
    level: 'Base',
    challenge: {
      id: 'desafio',
      kind: 'bug',
      q: 'O terminal responde "não é um comando do git". Toque na linha com o bug.',
      lines: ['git add .', 'git commit -m "pronto"', 'git pul origin main'],
      bugLine: 3,
      explain:
        'O comando é <code>git pull</code>, com dois L. Um erro de digitação e o Git não reconhece.',
    },
  },
];
