import type { Badge } from '@/domain/badges';

/**
 * As 51 insignias do jogo, portadas verbatim do manifesto fornecido pelo autor
 * (id, trail, name, description, crown, unlockedBy) -- só o campo `file` foi reescrito
 * do caminho de extração ("insignias/<trilha>/<id>.webp") para o caminho servido
 * em /public ("<trilha>/<id>.webp", relativo a /badges/).
 */
export function getBadgeById(id: string): Badge | undefined {
  return badgeCatalog.find((b) => b.id === id);
}

/**
 * O campo `trail` do catálogo (logica/sql/git/outras) é o "slug" do manifesto do autor,
 * que não é sempre igual ao `Trail.id` real usado em content/registry.ts.
 */
export const BADGE_TRAIL_TO_TRAIL_ID: Record<string, string> = {
  logica: 'logica',
  sql: 'banco-de-dados',
  git: 'git-github',
  python: 'python',
  java: 'java',
  php: 'php',
};

export const badgeCatalog: Badge[] = [
  {
    id: "logica",
    trail: "logica",
    name: "Lógica Básica",
    description: "Entendeu o que é algoritmo, variáveis e expressões.",
    crown: false,
    unlockedBy: "origem",
    file: "logica/logica.webp",
  },
  {
    id: "algoritmos",
    trail: "logica",
    name: "Algoritmos",
    description: "Escreveu o primeiro Olá, Mundo, em quatro linguagens.",
    crown: false,
    unlockedBy: "ola",
    file: "logica/algoritmos.webp",
  },
  {
    id: "tipos",
    trail: "logica",
    name: "Tipos de Dados",
    description: "Usou o tipo certo para cada informação.",
    crown: false,
    unlockedBy: "variaveis",
    file: "logica/tipos.webp",
  },
  {
    id: "operadores",
    trail: "logica",
    name: "Operadores",
    description: "Comparou, calculou e manipulou valores.",
    crown: false,
    unlockedBy: "operadores",
    file: "logica/operadores.webp",
  },
  {
    id: "logicos",
    trail: "logica",
    name: "Operadores Lógicos",
    description: "Combinou condições com E, OU e NÃO.",
    crown: false,
    unlockedBy: "operadores",
    file: "logica/logicos.webp",
  },
  {
    id: "controle",
    trail: "logica",
    name: "Estruturas de Controle",
    description: "Tomou decisões com if, else e switch.",
    crown: false,
    unlockedBy: "decisoes",
    file: "logica/controle.webp",
  },
  {
    id: "loops",
    trail: "logica",
    name: "Loops",
    description: "Repetiu tarefas de forma eficiente.",
    crown: false,
    unlockedBy: "loops",
    file: "logica/loops.webp",
  },
  {
    id: "arrays",
    trail: "logica",
    name: "Vetores e Arrays",
    description: "Organizou e acessou dados em coleções.",
    crown: false,
    unlockedBy: "arrays",
    file: "logica/arrays.webp",
  },
  {
    id: "matrizes",
    trail: "logica",
    name: "Matrizes",
    description: "Trabalhou com dados em duas dimensões.",
    crown: false,
    unlockedBy: "arrays",
    file: "logica/matrizes.webp",
  },
  {
    id: "funcoes",
    trail: "logica",
    name: "Funções",
    description: "Dividiu o código em blocos reutilizáveis.",
    crown: false,
    unlockedBy: "funcoes",
    file: "logica/funcoes.webp",
  },
  {
    id: "modulos",
    trail: "logica",
    name: "Módulos e Pacotes",
    description: "Organizou o código em arquivos que conversam entre si.",
    crown: false,
    unlockedBy: "web",
    file: "logica/modulos.webp",
  },
  {
    id: "depuracao",
    trail: "logica",
    name: "Depuração",
    description: "Encontrou e corrigiu o bug do tabuleiro cheio.",
    crown: false,
    unlockedBy: "velha",
    file: "logica/depuracao.webp",
  },
  {
    id: "problemas",
    trail: "logica",
    name: "Resolução de Problemas",
    description: "Derrotou o Loopus Infinitus. Esta insígnia reúne todas as outras.",
    crown: true,
    unlockedBy: "boss",
    file: "logica/problemas.webp",
  },
  {
    id: "sql-logica",
    trail: "sql",
    name: "Lógica e Estrutura",
    description: "O começo de tudo: entendeu como os dados se organizam.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-logica.webp",
  },
  {
    id: "sql-basico",
    trail: "sql",
    name: "SQL Básico",
    description: "Escreveu consultas que revelam dados.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-basico.webp",
  },
  {
    id: "sql-modelagem",
    trail: "sql",
    name: "Modelagem de Dados",
    description: "Organizou os dados: organização é poder.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-modelagem.webp",
  },
  {
    id: "sql-normalizacao",
    trail: "sql",
    name: "Normalização",
    description: "Eliminou a repetição de dados.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-normalizacao.webp",
  },
  {
    id: "sql-indices",
    trail: "sql",
    name: "Índices",
    description: "Deixou o acesso mais rápido.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-indices.webp",
  },
  {
    id: "sql-backup",
    trail: "sql",
    name: "Backup e Recuperação",
    description: "Ficou sempre preparado.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-backup.webp",
  },
  {
    id: "sql-transacoes",
    trail: "sql",
    name: "Transações",
    description: "Manteve tudo consistente do começo ao fim.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-transacoes.webp",
  },
  {
    id: "sql-indices-av",
    trail: "sql",
    name: "Índices Avançados",
    description: "Eficiência em grande escala.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-indices-av.webp",
  },
  {
    id: "sql-procedures",
    trail: "sql",
    name: "Procedimentos Armazenados",
    description: "Automatizou rotinas dentro do banco.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-procedures.webp",
  },
  {
    id: "sql-views",
    trail: "sql",
    name: "Views e Gatilhos",
    description: "Ganhou mais flexibilidade.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-views.webp",
  },
  {
    id: "sql-otimizacao",
    trail: "sql",
    name: "Otimização",
    description: "Extraiu o melhor desempenho.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-otimizacao.webp",
  },
  {
    id: "sql-bigdata",
    trail: "sql",
    name: "Big Data",
    description: "Encarou grandes volumes de dados.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-bigdata.webp",
  },
  {
    id: "sql-cloud",
    trail: "sql",
    name: "Cloud e Conectividade",
    description: "Dados em qualquer lugar.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-cloud.webp",
  },
  {
    id: "sql-apis",
    trail: "sql",
    name: "APIs e Integrações",
    description: "Fez sistemas conversarem entre si.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-apis.webp",
  },
  {
    id: "sql-deploy",
    trail: "sql",
    name: "Deploy",
    description: "Levou o código à produção.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-deploy.webp",
  },
  {
    id: "sql-mestre",
    trail: "sql",
    name: "Arquitetura de Dados",
    description: "Escalável e segura: a coroa da trilha de SQL.",
    crown: true,
    unlockedBy: null,
    file: "sql/sql-mestre.webp",
  },
  {
    id: "git-iniciante",
    trail: "git",
    name: "Iniciante",
    description: "Instalou o Git e configurou o primeiro repositório.",
    crown: false,
    unlockedBy: null,
    file: "git/git-iniciante.webp",
  },
  {
    id: "git-commit",
    trail: "git",
    name: "Primeiro Commit",
    description: "Fez o primeiro commit e salvou o código.",
    crown: false,
    unlockedBy: null,
    file: "git/git-commit.webp",
  },
  {
    id: "git-branch",
    trail: "git",
    name: "Ramificação",
    description: "Criou e trabalhou em branches.",
    crown: false,
    unlockedBy: null,
    file: "git/git-branch.webp",
  },
  {
    id: "git-merge",
    trail: "git",
    name: "Merge",
    description: "Uniu o código com a branch principal.",
    crown: false,
    unlockedBy: null,
    file: "git/git-merge.webp",
  },
  {
    id: "git-push",
    trail: "git",
    name: "Push",
    description: "Enviou as alterações para o remoto.",
    crown: false,
    unlockedBy: null,
    file: "git/git-push.webp",
  },
  {
    id: "git-pull",
    trail: "git",
    name: "Pull",
    description: "Baixou as atualizações do repositório.",
    crown: false,
    unlockedBy: null,
    file: "git/git-pull.webp",
  },
  {
    id: "gh-github",
    trail: "git",
    name: "GitHub",
    description: "Criou a conta e o primeiro repositório.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-github.webp",
  },
  {
    id: "gh-colab",
    trail: "git",
    name: "Colaboração",
    description: "Fez o primeiro pull request e recebeu feedback.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-colab.webp",
  },
  {
    id: "gh-issues",
    trail: "git",
    name: "Issues",
    description: "Registrou e acompanhou problemas.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-issues.webp",
  },
  {
    id: "gh-projects",
    trail: "git",
    name: "Projects",
    description: "Organizou o trabalho com quadros.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-projects.webp",
  },
  {
    id: "gh-actions",
    trail: "git",
    name: "Ações (Actions)",
    description: "Automatizou testes e deploy.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-actions.webp",
  },
  {
    id: "gh-pages",
    trail: "git",
    name: "Pages",
    description: "Publicou um site com o GitHub Pages.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-pages.webp",
  },
  {
    id: "gh-contrib",
    trail: "git",
    name: "Contribuição",
    description: "Contribuiu para projetos open source.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-contrib.webp",
  },
  {
    id: "gh-review",
    trail: "git",
    name: "Code Review",
    description: "Revisou código e aprendeu com o time.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-review.webp",
  },
  {
    id: "git-flow",
    trail: "git",
    name: "Git Flow",
    description: "Dominou o fluxo de trabalho.",
    crown: false,
    unlockedBy: null,
    file: "git/git-flow.webp",
  },
  {
    id: "gh-security",
    trail: "git",
    name: "Security",
    description: "Protegeu o repositório e as chaves.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-security.webp",
  },
  {
    id: "gh-devops",
    trail: "git",
    name: "DevOps",
    description: "Integrou com Docker, CI/CD e deploy.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-devops.webp",
  },
  {
    id: "git-mestre",
    trail: "git",
    name: "Mestre do Git e GitHub",
    description: "Domina controle de versão, colaboração e deploy: a coroa da trilha.",
    crown: true,
    unlockedBy: null,
    file: "git/git-mestre.webp",
  },
  {
    id: "estruturas",
    trail: "outras",
    name: "Estruturas de Dados",
    description: "Armazenar dados de forma organizada.",
    crown: false,
    unlockedBy: null,
    file: "outras/estruturas.webp",
  },
  {
    id: "poo",
    trail: "outras",
    name: "Orientação a Objetos",
    description: "Modelar o mundo real com classes e objetos.",
    crown: false,
    unlockedBy: null,
    file: "outras/poo.webp",
  },
  {
    id: "arquivos",
    trail: "outras",
    name: "Manipulação de Arquivos",
    description: "Ler e escrever dados no sistema.",
    crown: false,
    unlockedBy: null,
    file: "outras/arquivos.webp",
  },
  {
    id: "recursao",
    trail: "outras",
    name: "Recursividade",
    description: "Resolver problemas com autorreferência.",
    crown: false,
    unlockedBy: null,
    file: "outras/recursao.webp",
  },
  {
    id: "py-nascimento",
    trail: "python",
    name: "Nascimento de uma Linguagem",
    description: "Descobriu como e por que Python nasceu em 1989.",
    crown: false,
    unlockedBy: "nascimento-python",
    file: "python/nascimento.webp",
  },
  {
    id: "py-sintaxe",
    trail: "python",
    name: "Sintaxe Limpa",
    description: "Entendeu por que a indentação é a gramática de Python.",
    crown: false,
    unlockedBy: "sintaxe-e-tipos",
    file: "python/sintaxe.webp",
  },
  {
    id: "py-operadores",
    trail: "python",
    name: "Decisões",
    description: "Usou operadores e condições para ramificar o código.",
    crown: false,
    unlockedBy: "operadores-condicoes",
    file: "python/operadores.webp",
  },
  {
    id: "py-loops",
    trail: "python",
    name: "Repetição",
    description: "Dominou for, while e o range().",
    crown: false,
    unlockedBy: "loops-python",
    file: "python/loops.webp",
  },
  {
    id: "py-colecoes",
    trail: "python",
    name: "Coleções",
    description: "Organizou dados em listas, tuplas, dicionários e conjuntos.",
    crown: false,
    unlockedBy: "colecoes",
    file: "python/colecoes.webp",
  },
  {
    id: "py-funcoes",
    trail: "python",
    name: "Funções",
    description: "Empacotou lógica em funções reutilizáveis.",
    crown: false,
    unlockedBy: "funcoes-python",
    file: "python/funcoes.webp",
  },
  {
    id: "py-modulos",
    trail: "python",
    name: "Módulos e Arquivos",
    description: "Importou pacotes e leu/escreveu arquivos de verdade.",
    crown: false,
    unlockedBy: "modulos-e-arquivos",
    file: "python/modulos.webp",
  },
  {
    id: "py-poo",
    trail: "python",
    name: "Orientação a Objetos",
    description: "Modelou o mundo com classes e objetos em Python.",
    crown: false,
    unlockedBy: "poo-python",
    file: "python/poo.webp",
  },
  {
    id: "py-rara",
    trail: "python",
    name: "Guardião da Lua de Python",
    description: "Concluiu os 8 faróis da Lua de Python: pronto para encarar Onduluk.",
    crown: false,
    rare: true,
    unlockedBy: "trophy",
    file: "python/rara.svg",
  },
  {
    id: "py-onduluk",
    trail: "python",
    name: "Domador de Onduluk",
    description: "Derrotou Onduluk, a Serpente da Indentação: a coroa da Lua de Python.",
    crown: true,
    unlockedBy: "boss",
    file: "python/onduluk.webp",
  },
  {
    id: "java-nascimento",
    trail: "java",
    name: "Nascimento de uma Linguagem",
    description: "Descobriu como e por que Java nasceu em 1991, dentro do Green Project.",
    crown: false,
    unlockedBy: "nascimento-java",
    file: "java/nascimento.webp",
  },
  {
    id: "java-sintaxe",
    trail: "java",
    name: "Sintaxe Rígida",
    description: "Entendeu chaves, ponto e vírgula e a tipagem estática de Java.",
    crown: false,
    unlockedBy: "sintaxe-tipos-java",
    file: "java/sintaxe.webp",
  },
  {
    id: "java-operadores",
    trail: "java",
    name: "Decisões",
    description: "Usou operadores e condições, e aprendeu a diferença entre == e equals().",
    crown: false,
    unlockedBy: "operadores-condicoes-java",
    file: "java/operadores.webp",
  },
  {
    id: "java-loops",
    trail: "java",
    name: "Repetição",
    description: "Dominou for, while, do-while e o for-each.",
    crown: false,
    unlockedBy: "loops-java",
    file: "java/loops.webp",
  },
  {
    id: "java-colecoes",
    trail: "java",
    name: "Arrays e Coleções",
    description: "Organizou dados em arrays de tamanho fixo e em ArrayList.",
    crown: false,
    unlockedBy: "arrays-colecoes-java",
    file: "java/colecoes.webp",
  },
  {
    id: "java-metodos",
    trail: "java",
    name: "Métodos",
    description: "Empacotou lógica em métodos, com parâmetros e retorno tipados.",
    crown: false,
    unlockedBy: "metodos-java",
    file: "java/metodos.webp",
  },
  {
    id: "java-classes",
    trail: "java",
    name: "Classes e Objetos",
    description: "Modelou o mundo com classes, construtores e encapsulamento.",
    crown: false,
    unlockedBy: "classes-objetos-java",
    file: "java/classes.webp",
  },
  {
    id: "java-heranca",
    trail: "java",
    name: "Herança e Interfaces",
    description: "Reaproveitou comportamento com extends e implements.",
    crown: false,
    unlockedBy: "heranca-interfaces-java",
    file: "java/heranca.webp",
  },
  {
    id: "java-rara",
    trail: "java",
    name: "Guardião da Lua de Java",
    description: "Concluiu os 8 faróis da Lua de Java: pronto para encarar Nulo.",
    crown: false,
    rare: true,
    unlockedBy: "trophy",
    file: "java/rara.webp",
  },
  {
    id: "java-nulo",
    trail: "java",
    name: "Domador de Nulo",
    description: "Derrotou Nulo, o Erro de Um Bilhão de Dólares: a coroa da Lua de Java.",
    crown: true,
    unlockedBy: "boss",
    file: "java/nulo.webp",
  },
  {
    id: "php-nascimento",
    trail: "php",
    name: "Nascimento de uma Linguagem",
    description: "Descobriu como e por que PHP nasceu em 1994, como ferramenta pessoal de Rasmus Lerdorf.",
    crown: false,
    unlockedBy: "nascimento-php",
    file: "php/nascimento.webp",
  },
  {
    id: "php-sintaxe",
    trail: "php",
    name: "Sintaxe e Tipos",
    description: "Entendeu as tags <?php ?>, o $ das variáveis e a tipagem dinâmica de PHP.",
    crown: false,
    unlockedBy: "sintaxe-tipos-php",
    file: "php/sintaxe.webp",
  },
  {
    id: "php-operadores",
    trail: "php",
    name: "Decisões",
    description: "Usou operadores e condições, e aprendeu a diferença entre == e ===.",
    crown: false,
    unlockedBy: "operadores-condicoes-php",
    file: "php/operadores.webp",
  },
  {
    id: "php-loops",
    trail: "php",
    name: "Repetição",
    description: "Dominou for, while, do-while e o foreach.",
    crown: false,
    unlockedBy: "loops-php",
    file: "php/loops.webp",
  },
  {
    id: "php-colecoes",
    trail: "php",
    name: "Arrays Associativos",
    description: "Organizou dados em arrays indexados e associativos.",
    crown: false,
    unlockedBy: "arrays-php",
    file: "php/colecoes.webp",
  },
  {
    id: "php-funcoes",
    trail: "php",
    name: "Funções",
    description: "Empacotou lógica em funções, com argumentos padrão e variádicos.",
    crown: false,
    unlockedBy: "funcoes-php",
    file: "php/funcoes.webp",
  },
  {
    id: "php-poo",
    trail: "php",
    name: "Orientação a Objetos",
    description: "Modelou o mundo com classes e objetos em PHP.",
    crown: false,
    unlockedBy: "poo-php",
    file: "php/classes.webp",
  },
  {
    id: "php-web",
    trail: "php",
    name: "Superglobais e Web",
    description: "Usou $_GET, $_POST e $_SESSION para conversar com formulários e navegadores.",
    crown: false,
    unlockedBy: "superglobais-web-php",
    file: "php/web.webp",
  },
  {
    id: "php-rara",
    trail: "php",
    name: "Guardião da Lua de PHP",
    description: "Concluiu os 8 faróis da Lua de PHP: pronto para encarar Malabari.",
    crown: false,
    rare: true,
    unlockedBy: "trophy",
    file: "php/rara.webp",
  },
  {
    id: "php-malabari",
    trail: "php",
    name: "Domador de Malabari",
    description: "Derrotou Malabari, o Mestre da Comparação Solta: a coroa da Lua de PHP.",
    crown: true,
    unlockedBy: "boss",
    file: "php/malabari.webp",
  },
];
