import type { Badge } from '@/domain/badges';

/**
 * As 51 insignias do jogo, portadas verbatim do manifesto fornecido pelo autor
 * (id, trail, name, description, crown, unlockedBy) -- só o campo `file` foi reescrito
 * do caminho de extração ("insignias/<trilha>/<id>.webp") para o caminho servido
 * em /public ("<trilha>/<id>.webp", relativo a /badges/).
 */
export const badgeCatalog: Badge[] = [
  {
    id: "logica",
    trail: "logica",
    name: "Lógica Básica",
    description: "Entendeu o que é algoritmo, variáveis e expressões.",
    crown: false,
    unlockedBy: "origem",
    file: "logica/logica.webp",
  },
  {
    id: "algoritmos",
    trail: "logica",
    name: "Algoritmos",
    description: "Escreveu o primeiro Olá, Mundo, em quatro linguagens.",
    crown: false,
    unlockedBy: "ola",
    file: "logica/algoritmos.webp",
  },
  {
    id: "tipos",
    trail: "logica",
    name: "Tipos de Dados",
    description: "Usou o tipo certo para cada informação.",
    crown: false,
    unlockedBy: "variaveis",
    file: "logica/tipos.webp",
  },
  {
    id: "operadores",
    trail: "logica",
    name: "Operadores",
    description: "Comparou, calculou e manipulou valores.",
    crown: false,
    unlockedBy: "operadores",
    file: "logica/operadores.webp",
  },
  {
    id: "logicos",
    trail: "logica",
    name: "Operadores Lógicos",
    description: "Combinou condições com E, OU e NÃO.",
    crown: false,
    unlockedBy: "operadores",
    file: "logica/logicos.webp",
  },
  {
    id: "controle",
    trail: "logica",
    name: "Estruturas de Controle",
    description: "Tomou decisões com if, else e switch.",
    crown: false,
    unlockedBy: "decisoes",
    file: "logica/controle.webp",
  },
  {
    id: "loops",
    trail: "logica",
    name: "Loops",
    description: "Repetiu tarefas de forma eficiente.",
    crown: false,
    unlockedBy: "loops",
    file: "logica/loops.webp",
  },
  {
    id: "arrays",
    trail: "logica",
    name: "Vetores e Arrays",
    description: "Organizou e acessou dados em coleções.",
    crown: false,
    unlockedBy: "arrays",
    file: "logica/arrays.webp",
  },
  {
    id: "matrizes",
    trail: "logica",
    name: "Matrizes",
    description: "Trabalhou com dados em duas dimensões.",
    crown: false,
    unlockedBy: "arrays",
    file: "logica/matrizes.webp",
  },
  {
    id: "funcoes",
    trail: "logica",
    name: "Funções",
    description: "Dividiu o código em blocos reutilizáveis.",
    crown: false,
    unlockedBy: "funcoes",
    file: "logica/funcoes.webp",
  },
  {
    id: "modulos",
    trail: "logica",
    name: "Módulos e Pacotes",
    description: "Organizou o código em arquivos que conversam entre si.",
    crown: false,
    unlockedBy: "web",
    file: "logica/modulos.webp",
  },
  {
    id: "depuracao",
    trail: "logica",
    name: "Depuração",
    description: "Encontrou e corrigiu o bug do tabuleiro cheio.",
    crown: false,
    unlockedBy: "velha",
    file: "logica/depuracao.webp",
  },
  {
    id: "problemas",
    trail: "logica",
    name: "Resolução de Problemas",
    description: "Derrotou o Loopus Infinitus. Esta insígnia reúne todas as outras.",
    crown: true,
    unlockedBy: "boss",
    file: "logica/problemas.webp",
  },
  {
    id: "sql-logica",
    trail: "sql",
    name: "Lógica e Estrutura",
    description: "O começo de tudo: entendeu como os dados se organizam.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-logica.webp",
  },
  {
    id: "sql-basico",
    trail: "sql",
    name: "SQL Básico",
    description: "Escreveu consultas que revelam dados.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-basico.webp",
  },
  {
    id: "sql-modelagem",
    trail: "sql",
    name: "Modelagem de Dados",
    description: "Organizou os dados: organização é poder.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-modelagem.webp",
  },
  {
    id: "sql-normalizacao",
    trail: "sql",
    name: "Normalização",
    description: "Eliminou a repetição de dados.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-normalizacao.webp",
  },
  {
    id: "sql-indices",
    trail: "sql",
    name: "Índices",
    description: "Deixou o acesso mais rápido.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-indices.webp",
  },
  {
    id: "sql-backup",
    trail: "sql",
    name: "Backup e Recuperação",
    description: "Ficou sempre preparado.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-backup.webp",
  },
  {
    id: "sql-transacoes",
    trail: "sql",
    name: "Transações",
    description: "Manteve tudo consistente do começo ao fim.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-transacoes.webp",
  },
  {
    id: "sql-indices-av",
    trail: "sql",
    name: "Índices Avançados",
    description: "Eficiência em grande escala.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-indices-av.webp",
  },
  {
    id: "sql-procedures",
    trail: "sql",
    name: "Procedimentos Armazenados",
    description: "Automatizou rotinas dentro do banco.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-procedures.webp",
  },
  {
    id: "sql-views",
    trail: "sql",
    name: "Views e Gatilhos",
    description: "Ganhou mais flexibilidade.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-views.webp",
  },
  {
    id: "sql-otimizacao",
    trail: "sql",
    name: "Otimização",
    description: "Extraiu o melhor desempenho.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-otimizacao.webp",
  },
  {
    id: "sql-bigdata",
    trail: "sql",
    name: "Big Data",
    description: "Encarou grandes volumes de dados.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-bigdata.webp",
  },
  {
    id: "sql-cloud",
    trail: "sql",
    name: "Cloud e Conectividade",
    description: "Dados em qualquer lugar.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-cloud.webp",
  },
  {
    id: "sql-apis",
    trail: "sql",
    name: "APIs e Integrações",
    description: "Fez sistemas conversarem entre si.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-apis.webp",
  },
  {
    id: "sql-deploy",
    trail: "sql",
    name: "Deploy",
    description: "Levou o código à produção.",
    crown: false,
    unlockedBy: null,
    file: "sql/sql-deploy.webp",
  },
  {
    id: "sql-mestre",
    trail: "sql",
    name: "Arquitetura de Dados",
    description: "Escalável e segura: a coroa da trilha de SQL.",
    crown: true,
    unlockedBy: null,
    file: "sql/sql-mestre.webp",
  },
  {
    id: "git-iniciante",
    trail: "git",
    name: "Iniciante",
    description: "Instalou o Git e configurou o primeiro repositório.",
    crown: false,
    unlockedBy: null,
    file: "git/git-iniciante.webp",
  },
  {
    id: "git-commit",
    trail: "git",
    name: "Primeiro Commit",
    description: "Fez o primeiro commit e salvou o código.",
    crown: false,
    unlockedBy: null,
    file: "git/git-commit.webp",
  },
  {
    id: "git-branch",
    trail: "git",
    name: "Ramificação",
    description: "Criou e trabalhou em branches.",
    crown: false,
    unlockedBy: null,
    file: "git/git-branch.webp",
  },
  {
    id: "git-merge",
    trail: "git",
    name: "Merge",
    description: "Uniu o código com a branch principal.",
    crown: false,
    unlockedBy: null,
    file: "git/git-merge.webp",
  },
  {
    id: "git-push",
    trail: "git",
    name: "Push",
    description: "Enviou as alterações para o remoto.",
    crown: false,
    unlockedBy: null,
    file: "git/git-push.webp",
  },
  {
    id: "git-pull",
    trail: "git",
    name: "Pull",
    description: "Baixou as atualizações do repositório.",
    crown: false,
    unlockedBy: null,
    file: "git/git-pull.webp",
  },
  {
    id: "gh-github",
    trail: "git",
    name: "GitHub",
    description: "Criou a conta e o primeiro repositório.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-github.webp",
  },
  {
    id: "gh-colab",
    trail: "git",
    name: "Colaboração",
    description: "Fez o primeiro pull request e recebeu feedback.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-colab.webp",
  },
  {
    id: "gh-issues",
    trail: "git",
    name: "Issues",
    description: "Registrou e acompanhou problemas.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-issues.webp",
  },
  {
    id: "gh-projects",
    trail: "git",
    name: "Projects",
    description: "Organizou o trabalho com quadros.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-projects.webp",
  },
  {
    id: "gh-actions",
    trail: "git",
    name: "Ações (Actions)",
    description: "Automatizou testes e deploy.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-actions.webp",
  },
  {
    id: "gh-pages",
    trail: "git",
    name: "Pages",
    description: "Publicou um site com o GitHub Pages.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-pages.webp",
  },
  {
    id: "gh-contrib",
    trail: "git",
    name: "Contribuição",
    description: "Contribuiu para projetos open source.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-contrib.webp",
  },
  {
    id: "gh-review",
    trail: "git",
    name: "Code Review",
    description: "Revisou código e aprendeu com o time.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-review.webp",
  },
  {
    id: "git-flow",
    trail: "git",
    name: "Git Flow",
    description: "Dominou o fluxo de trabalho.",
    crown: false,
    unlockedBy: null,
    file: "git/git-flow.webp",
  },
  {
    id: "gh-security",
    trail: "git",
    name: "Security",
    description: "Protegeu o repositório e as chaves.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-security.webp",
  },
  {
    id: "gh-devops",
    trail: "git",
    name: "DevOps",
    description: "Integrou com Docker, CI/CD e deploy.",
    crown: false,
    unlockedBy: null,
    file: "git/gh-devops.webp",
  },
  {
    id: "git-mestre",
    trail: "git",
    name: "Mestre do Git e GitHub",
    description: "Domina controle de versão, colaboração e deploy: a coroa da trilha.",
    crown: true,
    unlockedBy: null,
    file: "git/git-mestre.webp",
  },
  {
    id: "estruturas",
    trail: "outras",
    name: "Estruturas de Dados",
    description: "Armazenar dados de forma organizada.",
    crown: false,
    unlockedBy: null,
    file: "outras/estruturas.webp",
  },
  {
    id: "poo",
    trail: "outras",
    name: "Orientação a Objetos",
    description: "Modelar o mundo real com classes e objetos.",
    crown: false,
    unlockedBy: null,
    file: "outras/poo.webp",
  },
  {
    id: "arquivos",
    trail: "outras",
    name: "Manipulação de Arquivos",
    description: "Ler e escrever dados no sistema.",
    crown: false,
    unlockedBy: null,
    file: "outras/arquivos.webp",
  },
  {
    id: "recursao",
    trail: "outras",
    name: "Recursividade",
    description: "Resolver problemas com autorreferência.",
    crown: false,
    unlockedBy: null,
    file: "outras/recursao.webp",
  },
];
