import type { Module } from '@/domain/trail/types';

/** Trilha 2 da Ramificação Django: apps, URLs e views. */
export const modDjangoViews: Module = {
  id: 'django-views',
  short: 'Apps, URLs e views',
  title: 'Apps, URLs e views: o caminho de um pedido',
  lead: 'Quando alguém abre uma página, o Django procura a URL no mapa e chama uma função: a view. Ela devolve a resposta.',
  level: 'Base',
  blocks: [
    { t: 'h', x: 'Projeto x app' },
    {
      t: 'p',
      x: 'O <b>projeto</b> é o site inteiro. Um <b>app</b> é uma parte com uma função só: uma enquete, um blog, uma loja. Um projeto pode ter vários apps.',
    },
    { t: 'code', file: 'terminal', lang: 'bash', nolab: true, x: 'python manage.py startapp enquetes' },
    { t: 'h', x: 'A view: uma função que recebe o pedido' },
    { t: 'p', x: 'Toda view recebe o pedido (<code>request</code>) e devolve uma resposta. A mais simples devolve um texto:' },
    {
      t: 'code',
      file: 'enquetes/views.py',
      lang: 'python',
      nolab: true,
      x: 'from django.http import HttpResponse\n\n\ndef index(request):\n    return HttpResponse("Olá! Esta é a página das enquetes.")',
    },
    { t: 'h', x: 'Ligando a URL à view' },
    { t: 'p', x: 'Cada app pode ter o seu <code>urls.py</code>, com uma lista chamada <code>urlpatterns</code>:' },
    {
      t: 'code',
      file: 'enquetes/urls.py',
      lang: 'python',
      nolab: true,
      x: 'from django.urls import path\n\nfrom . import views\n\nurlpatterns = [\n    path("", views.index, name="index"),\n]',
    },
    { t: 'p', x: 'Depois, o <code>urls.py</code> do projeto inclui as URLs do app com <code>include()</code>:' },
    {
      t: 'code',
      file: 'meusite/urls.py',
      lang: 'python',
      nolab: true,
      x: 'from django.contrib import admin\nfrom django.urls import include, path\n\nurlpatterns = [\n    path("enquetes/", include("enquetes.urls")),\n    path("admin/", admin.site.urls),\n]',
    },
    { t: 'flow', items: ['Navegador pede /enquetes/', 'meusite/urls.py', 'enquetes/urls.py', 'views.index', 'HttpResponse'] },
    { t: 'h', x: 'Pegando um pedaço da URL' },
    { t: 'p', x: 'Com <code>&lt;int:pergunta_id&gt;</code> o Django lê um número da URL e entrega para a view como argumento:' },
    {
      t: 'code',
      file: 'enquetes/urls.py',
      lang: 'python',
      nolab: true,
      x: 'urlpatterns = [\n    path("", views.index, name="index"),\n    path("<int:pergunta_id>/", views.detalhe, name="detalhe"),\n]',
    },
    {
      t: 'code',
      file: 'enquetes/views.py',
      lang: 'python',
      nolab: true,
      x: 'def detalhe(request, pergunta_id):\n    return HttpResponse(f"Você está vendo a pergunta {pergunta_id}.")',
    },
    { t: 'say', x: 'Repare no caminho: a URL é o endereço, a view é quem atende a porta. Se o endereço não estiver no mapa, o Django responde 404.' },
    {
      t: 'note',
      k: 'Fonte oficial',
      x: 'Documentação do Django: <a href="https://docs.djangoproject.com/en/stable/intro/tutorial01/" target="_blank" rel="noopener">Tutorial, parte 1</a> e <a href="https://docs.djangoproject.com/en/stable/topics/http/urls/" target="_blank" rel="noopener">URL dispatcher</a>.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      q: 'Qual a diferença entre projeto e app no Django?',
      options: [
        'Não há diferença, são dois nomes para a mesma coisa',
        'O projeto é o site inteiro; um app é uma parte com uma função só',
        'O app é o site inteiro; o projeto é uma parte dele',
        'O projeto só existe em produção',
      ],
      answer: 1,
      explain: 'Um projeto junta configurações e vários apps. Cada app cuida de uma parte, como enquetes ou blog.',
    },
    {
      id: 'q2',
      q: 'Complete a view para que ela devolva um texto:',
      fill: true,
      pre: 'return',
      post: '("Olá!")',
      accept: ['HttpResponse'],
      wrong: ['print', 'render_template', 'Response'],
      placeholder: '?',
      explain: '<code>HttpResponse</code> vem de <code>django.http</code> e devolve a resposta ao navegador.',
    },
    {
      id: 'q3',
      kind: 'bug',
      q: 'A URL /enquetes/ dá 404. Toque na linha com o bug do meusite/urls.py.',
      lines: ['from django.urls import include, path', '', 'urlpatterns = [', '    path("enquetes/", "enquetes.urls"),', ']'],
      bugLine: 4,
      explain: 'As URLs do app entram com <code>include("enquetes.urls")</code>. Só o texto não diz ao Django para ler o outro arquivo.',
    },
    {
      id: 'desafio',
      kind: 'order',
      q: 'Desafio: monte a rota que liga o endereço vazio à view index.',
      pieces: ['path(', '""', ',', 'views.index', ')'],
      distractors: ['include(', 'views.index()', 'url('],
      explain: '<code>path("", views.index)</code> passa a função sem chamá-la: quem chama é o Django, quando o pedido chega.',
    },
  ],
};
