import type { Module } from '@/domain/trail/types';

/** Farol 4 da Lua de PHP: for, while, do-while e foreach (com chave => valor). */
export const modLoops: Module = {
  id: 'loops-php',
  short: 'Repetir com propósito',
  title: 'Laços: for, while, do-while e foreach',
  lead: 'PHP tem os mesmos quatro laços de Java, mas o foreach ganha um poder a mais: percorrer chave e valor ao mesmo tempo.',
  level: 'Intermediário',
  blocks: [
    { t: 'h', x: 'for clássico' },
    {
      t: 'code',
      file: 'for.php',
      lang: 'php',
      nolab: true,
      x: 'for ($i = 0; $i < 3; $i++) {\n    echo $i;\n}',
    },
    {
      t: 'out',
      file: 'for.out',
      x: '012',
    },
    { t: 'h', x: 'while e do-while' },
    {
      t: 'code',
      file: 'while.php',
      lang: 'php',
      nolab: true,
      x: '$n = 0;\nwhile ($n < 3) {\n    echo $n;\n    $n++;\n}',
    },
    {
      t: 'code',
      file: 'doWhile.php',
      lang: 'php',
      nolab: true,
      x: '$tentativas = 0;\ndo {\n    echo "Tentativa $tentativas ";\n    $tentativas++;\n} while ($tentativas < 3);',
    },
    { t: 'h', x: 'foreach: percorrendo arrays direto' },
    {
      t: 'p',
      x: 'O <code>foreach</code> percorre um array sem precisar de índice manual. Para arrays associativos, dá para pegar a chave <b>e</b> o valor ao mesmo tempo, com <code>=&gt;</code>.',
    },
    {
      t: 'code',
      file: 'foreach.php',
      lang: 'php',
      nolab: true,
      x: '$frutas = ["maçã", "banana", "uva"];\n\nforeach ($frutas as $fruta) {\n    echo $fruta . "\\n";\n}',
    },
    {
      t: 'code',
      file: 'foreachChaveValor.php',
      lang: 'php',
      nolab: true,
      x: '$viajante = ["nome" => "Ana", "xp" => 150];\n\nforeach ($viajante as $chave => $valor) {\n    echo "$chave: $valor\\n";\n}',
    },
    {
      t: 'out',
      file: 'foreachChaveValor.out',
      x: 'nome: Ana\nxp: 150',
    },
    { t: 'h', x: 'break e continue' },
    {
      t: 'code',
      file: 'breakContinue.php',
      lang: 'php',
      nolab: true,
      x: 'for ($numero = 0; $numero < 10; $numero++) {\n    if ($numero == 5) {\n        break;\n    }\n    if ($numero % 2 == 0) {\n        continue;\n    }\n    echo $numero;\n}',
    },
  ],
  quiz: [
    {
      id: 'q1',
      afterBlock: 9,
      kind: "order",
      q: "Monte o laço que percorre o array $viajante pegando a chave e o valor",
      pieces: ["foreach", "($viajante", "as", "$chave", "=>", "$valor)"],
      distractors: ["in", ":"],
      explain: "<code>foreach ($viajante as $chave => $valor)</code> percorre o array pegando a chave e o valor ao mesmo tempo.",
    },
    {
      id: 'q2',
      q: 'Qual laço garante rodar o bloco pelo menos uma vez, mesmo que a condição já comece falsa?',
      options: ['for', 'while', 'do-while', 'foreach'],
      answer: 2,
      explain: 'No do-while, a condição só é testada depois do bloco rodar, garantindo pelo menos uma execução.',
    },
    {
      id: 'q3',
      q: 'O que for ($i = 0; $i < 3; $i++) { echo $i; } imprime?',
      options: ['0 1 2', '012', '123', '0123'],
      answer: 1,
      explain: 'echo sem separador junta os valores sem espaço: 0, 1, 2 saem colados como "012".',
    },
    {
      id: 'q4',
      kind: "output",
      q: "Repare no continue. O que aparece na tela?",
      lang: "php",
      code: "<?php\nfor ($i = 1; $i <= 4; $i++) {\n    if ($i == 2) {\n        continue;\n    }\n    echo $i;\n}",
      options: ["1", "134", "1234", "34"],
      answer: 1,
      explain: "<code>continue</code> pula o resto da volta atual (o echo do 2), sem sair do laço. Com <code>break</code>, apareceria só 1.",
    },
    {
      id: 'q5',
      q: 'Complete: para percorrer os itens de um array sem controlar um índice manualmente, PHP usa o laço ___.',
      fill: true,
      pre: 'Para percorrer os itens de um array sem controlar um índice manualmente, PHP usa o laço',
      post: '.',
      accept: ['foreach'],
      wrong: ['for', 'while', 'do'],
      placeholder: 'nome do laço',
      explain: 'foreach percorre cada item de um array diretamente, sem precisar de um índice manual como no for clássico.',
    },
  ],
};
