import type { GemSpec, WebBoss, WebEraTrail } from '@/domain/webEra';

/**
 * Era da Web: as 10 trilhas, o chefe Eco e as insígnias especiais. Base: o protótipo aprovado
 * (`docs/eras/web/Era_da_Web.html`), com a versão para iniciantes (`claude_Era_da_Web.html`):
 * falas curtas, código montado com blocos ou lacuna (digitar só na fase final e nos chefes) e
 * os minijogos de pressão (desarme, interrogatório, portal e poda). Docs: MDN e W3C.
 * `{NAME}` e `{USER}` viram o nome do viajante na tela.
 */

export const TAGS_HTML = ['<p>', '<h1>', '<h2>', '<body>', '<head>', '<title>', '<a>', '<img>', '<ul>', '<li>', '<main>', '<nav>', '<footer>', '<section>', '<button>'];
export const TAGS_FAKE = ['<pp>', '<titel>', '<bold>', '<hed>', '<imagem>', '<paragrafo>', '<botao>', '<lnk>', '<bodi>', '<h7>'];

export const BASE_CARDS = `<div class="grade">
  <div class="projeto">Projeto 1</div>
  <div class="projeto">Projeto 2</div>
  <div class="outro">Rascunho</div>
</div>`;

const DARK_HTML = '<style>.escuro{background:#111;color:#eee}</style><button id="tema">Tema</button>';

/** Cada trilha: missões curtas (ação) + 1 peça do portfólio. */
export const webEraTrails: WebEraTrail[] = [
  {
    id: 'w1',
    title: 'A Faísca da Web',
    year: '1989–1997',
    color: '#c3a6ff',
    gem: { badgeId: 'web-faisca', name: 'Faísca da Web', icon: 'globe', sides: 8, c1: '#d9c6ff', c2: '#5b2bd6', tier: 'comum' },
    piece: 'files',
    pieceName: 'pasta do projeto',
    say: ['CERN, 1989: Tim Berners-Lee inventa a Web.', 'O Eco quer apagar tudo. Bora consertar!'],
    doc: { label: 'W3C · história do CSS', url: 'https://www.w3.org/Style/CSS20/history.html' },
    rounds: [
      {
        type: 'order',
        title: 'Coloque a história em ordem',
        sub: 'Do mais antigo pro mais novo.',
        block: true,
        tokens: [
          '1989 · Tim propõe a Web no CERN',
          '1991 · “HTML Tags”: 18 tags',
          '1994 · Håkon Lie propõe o CSS',
          '1995 · JavaScript nasce na Netscape',
          '1996 · CSS1 vira recomendação do W3C',
          '1997 · JS padronizado como ECMAScript',
        ],
      },
      {
        type: 'sort',
        title: 'Quem faz o quê?',
        sub: 'Toque no dono de cada peça.',
        time: 30,
        maxErr: 3,
        buckets: [
          { id: 'h', label: 'HTML', s: 'estrutura', tone: 'html' },
          { id: 'c', label: 'CSS', s: 'aparência', tone: 'css' },
          { id: 'j', label: 'JS', s: 'comportamento', tone: 'js' },
        ],
        items: [
          ['título da página', 'h'],
          ['cor de fundo', 'c'],
          ['menu que abre ao clicar', 'j'],
          ['parágrafo de texto', 'h'],
          ['fonte maior', 'c'],
          ['contador de cliques', 'j'],
          ['link para outra página', 'h'],
          ['sombra no botão', 'c'],
          ['validar e-mail antes de enviar', 'j'],
          ['imagem', 'h'],
        ],
      },
      {
        type: 'catch',
        title: 'Pegue os arquivos da Web',
        sub: 'Só os que um site usa.',
        time: 25,
        need: 8,
        maxErr: 3,
        good: ['index.html', 'style.css', 'script.js', '.html', '.css', '.js', 'sobre.html', 'app.js'],
        bad: ['.exe', '.docx', '.mp3', '.psd', '.zip', '.pdf', '.xlsx'],
      },
    ],
  },
  {
    id: 'w2',
    title: 'Esqueleto HTML',
    year: '1991',
    color: '#ff7a3d',
    gem: { badgeId: 'web-esqueleto', name: 'Esqueleto de Tags', icon: 'skeleton', sides: 6, c1: '#ffb38a', c2: '#c2410c', tier: 'comum' },
    piece: 'title',
    pieceName: 'título da aba',
    say: ['Todo site nasce de um esqueleto HTML.', 'Monta rápido, viajante!'],
    doc: {
      label: 'MDN · estrutura de um documento',
      url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
    },
    rounds: [
      {
        type: 'order',
        title: 'Monte o esqueleto',
        sub: 'Toque de cima pra baixo.',
        block: true,
        preview: true,
        tokens: ['<!DOCTYPE html>', '<html lang="pt-BR">', '<head>', '<title>Meu Portfólio</title>', '</head>', '<body>', '<h1>Olá!</h1>', '</body>', '</html>'],
        extra: ['<bodi>', '</title>'],
      },
      { type: 'catch', title: 'Chuva de tags', sub: 'Pegue só tags que existem.', time: 25, need: 8, maxErr: 3, good: TAGS_HTML, bad: TAGS_FAKE },
      {
        type: 'blocks',
        lang: 'html',
        title: 'Dê nome à aba',
        sub: 'Monte o <head>. Olhe a aba mudar!',
        block: true,
        tab: true,
        tokens: ['<head>', '<title>Portfólio de {NAME}</title>', '</head>'],
        extra: ['<titel>Portfólio</titel>', '<body>'],
        capture: ({ doc }) => ({ title: doc.title.trim() }),
      },
    ],
  },
  {
    id: 'w3',
    title: 'Títulos e Textos',
    year: '1991',
    color: '#ff7a3d',
    gem: { badgeId: 'web-voz-h1', name: 'Voz do H1', icon: 'h1', sides: 8, c1: '#ffc38a', c2: '#d9480f', tier: 'comum' },
    piece: 'hero',
    pieceName: 'seu nome + bio',
    say: ['Agora o site precisa dizer quem você é.', 'Tudo aqui vai pro SEU portfólio.'],
    doc: {
      label: 'MDN · títulos e parágrafos',
      url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/Headings_and_paragraphs',
    },
    rounds: [
      {
        type: 'blocks',
        lang: 'html',
        title: 'Seu nome em destaque',
        sub: 'Monte o <h1> com seu nome.',
        tokens: ['<h1>', '{NAME}', '</h1>'],
        extra: ['<h7>', '</p>'],
        capture: ({ doc }) => ({ name: doc.querySelector('h1')?.textContent?.trim() }),
      },
      {
        type: 'bug',
        title: 'Caça aos bugs',
        sub: 'Toque nas 3 linhas quebradas.',
        time: 30,
        lines: ['<h1>Ana Souza</h2>', '<p>Dev em formação.</p>', '<p>Eu crio <strong>sites<strong></p>', '<h2>Projetos</h2>', '<p>Moro em Ipatinga<p>'],
        bad: [0, 2, 4],
      },
      {
        type: 'fill',
        lang: 'html',
        title: 'Sua bio',
        sub: 'Qual tag faz um parágrafo?',
        pre: '<h1>{NAME}</h1>\n<',
        options: ['p', 'h7', 'bio'],
        answer: 'p',
        post: '>Estudo programação e crio sites.</p>',
        capture: ({ doc }) => ({ bio: doc.querySelector('p')?.textContent?.trim() }),
      },
    ],
  },
  {
    id: 'w4',
    title: 'Links e Imagens',
    year: '1991–93',
    color: '#ff7a3d',
    gem: { badgeId: 'web-elo-hipertexto', name: 'Elo do Hipertexto', icon: 'link', sides: 10, c1: '#ffd08a', c2: '#b45309', tier: 'comum' },
    piece: 'links',
    pieceName: 'seus links',
    say: ['O “H” de HTML é de Hiper: texto que pula.', 'Links são o coração da Web.'],
    doc: {
      label: 'MDN · criando links',
      url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/Creating_links',
    },
    rounds: [
      {
        type: 'order',
        title: 'Monte o link',
        sub: 'Um link pro GitHub.',
        preview: true,
        tokens: ['<a', 'href="https://github.com"', 'target="_blank">', 'Meu GitHub', '</a>'],
        extra: ['src="github"'],
      },
      {
        type: 'prune',
        title: 'Poda',
        sub: '3 trechos, 1 inválido. Corte ele!',
        sets: [
          { snips: ['<a href="/sobre">Sobre</a>', '<a src="/sobre">Sobre</a>', '<a href="#topo">Topo</a>'], bad: 1, why: 'link usa href, não src' },
          { snips: ['<img src="eu.png" alt="Eu">', '<img href="eu.png" alt="Eu">', '<img src="logo.svg" alt="Logo">'], bad: 1, why: 'imagem usa src' },
          { snips: ['<a href="https://site.com">Site</a>', '<a href="mailto:oi@ana.dev">E-mail</a>', '<a href=https://site.com>Site<a>'], bad: 2, why: 'faltou fechar com </a>' },
        ],
      },
      {
        type: 'bug',
        title: 'Links quebrados',
        sub: 'Toque nos 3 erros.',
        time: 30,
        lines: [
          '<a href="https://linkedin.com">LinkedIn</a>',
          '<img src="eu.png">',
          '<a src="https://github.com">GitHub</a>',
          '<img src="logo.png" alt="Logo">',
          '<a href=https://site.com>Site</a>',
        ],
        bad: [1, 2, 4],
        why: ['', 'img sem alt: leitor de tela não sabe o que é', 'link usa href, não src', '', 'aspas no valor do atributo'],
      },
      {
        type: 'fill',
        lang: 'html',
        title: 'Seu link de verdade',
        sub: 'Qual atributo guarda o endereço?',
        pre: '<a ',
        options: ['href', 'src', 'link'],
        answer: 'href',
        post: '="https://github.com/{USER}">Meu GitHub</a>',
        capture: ({ doc }) => ({
          links: [...doc.querySelectorAll('a[href^="http"]')].slice(0, 4).map((a) => ({ href: a.getAttribute('href') ?? '', t: (a.textContent ?? '').trim() })),
        }),
      },
    ],
  },
  {
    id: 'w5',
    title: 'Semântica',
    year: '2014 · HTML5',
    color: '#ff7a3d',
    gem: { badgeId: 'web-arquiteto-semantico', name: 'Arquiteto Semântico', icon: 'layout', sides: 6, c1: '#ffa06b', c2: '#9a3412', tier: 'comum' },
    piece: 'sections',
    pieceName: 'seções do site',
    say: ['Tags com significado ajudam o Google e leitores de tela.', 'Divida o site em partes com nome.'],
    doc: {
      label: 'MDN · estrutura do site',
      url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/Structuring_documents',
    },
    rounds: [
      {
        type: 'order',
        title: 'Planta do site',
        sub: 'De cima pra baixo.',
        block: true,
        tokens: ['<header> logo e nome', '<nav> menu', '<main> conteúdo principal', '<footer> rodapé'],
      },
      {
        type: 'sort',
        title: 'Onde isso mora?',
        sub: 'Toque onde cada parte mora.',
        time: 30,
        maxErr: 3,
        buckets: [
          { id: 'h', label: '<header>', tone: 'html' },
          { id: 'n', label: '<nav>', tone: 'violet' },
          { id: 'm', label: '<main>', tone: 'css' },
          { id: 'f', label: '<footer>', tone: 'js' },
        ],
        items: [
          ['nome e logo', 'h'],
          ['links: Sobre · Projetos · Contato', 'n'],
          ['lista de projetos', 'm'],
          ['© 2026 Ana', 'f'],
          ['texto “sobre mim”', 'm'],
          ['menu hambúrguer', 'n'],
        ],
      },
      {
        type: 'catch',
        title: 'Só tags semânticas',
        sub: '<div> e <span> não contam!',
        time: 25,
        need: 8,
        maxErr: 3,
        good: ['<header>', '<nav>', '<main>', '<section>', '<article>', '<footer>', '<aside>', '<figure>'],
        bad: ['<div>', '<span>', '<b>', '<font>', '<center>', '<i>'],
      },
    ],
  },
  {
    id: 'w6',
    title: 'Seletores e Cores',
    year: '1994 · CSS',
    color: '#3db8ff',
    gem: { badgeId: 'web-pincel-neon', name: 'Pincel Neon', icon: 'brush', sides: 8, c1: '#8ad8ff', c2: '#1d4ed8', tier: 'comum' },
    piece: 'color',
    pieceName: 'cor do seu site',
    say: ['1994: Håkon Lie propõe o CSS.', 'Conteúdo num lugar, aparência no outro!'],
    doc: {
      label: 'MDN · seletores CSS',
      url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
    },
    rounds: [
      {
        type: 'fill',
        lang: 'css',
        title: 'Pinte seu nome',
        sub: 'Escolha a cor do SEU site.',
        html: '<h1>{NAME}</h1><p>Portfólio</p>',
        pre: 'h1 {\n  color: ',
        options: ['tomato', 'deepskyblue', 'hotpink', 'cor-rosa'],
        answer: ['tomato', 'deepskyblue', 'hotpink'],
        post: ';\n}',
        capture: ({ win, doc }) => {
          const h = doc.querySelector('h1');
          return h ? { color: win.getComputedStyle(h).color } : {};
        },
      },
      {
        type: 'catch',
        title: 'Seletores válidos',
        sub: 'Pegue só CSS que funciona.',
        time: 25,
        need: 8,
        maxErr: 3,
        good: ['h1', '.card', '#topo', 'nav a', 'p:hover', '*', '.btn.ativo', 'ul > li'],
        bad: ['..card', '#', '<p>', 'h1{', 'cor:azul', '.', '@@'],
      },
      {
        type: 'prune',
        title: 'Poda do CSS',
        sub: 'Corte a regra quebrada.',
        sets: [
          { snips: ['h1 { color: red; }', 'h1 ( color: red; )', 'p { font-size: 20px; }'], bad: 1, why: 'CSS usa chaves { }' },
          { snips: ['.card { padding: 8px; }', '.card { padding 8px; }', '#topo { margin: 0; }'], bad: 1, why: 'faltaram os dois-pontos' },
          { snips: ['a:hover { color: gold; }', 'nav a { color: white; }', 'a hover { color: gold; }'], bad: 2, why: ':hover leva dois-pontos' },
        ],
      },
      {
        type: 'fill',
        lang: 'css',
        title: 'Mira no alvo',
        sub: 'Só os .projeto ganham borda.',
        html: BASE_CARDS,
        pre: '',
        options: ['.projeto', 'projeto', '#projeto'],
        answer: '.projeto',
        post: ' { border: 2px solid deeppink; }',
      },
    ],
  },
  {
    id: 'w7',
    title: 'Box Model',
    year: '1996 · CSS1',
    color: '#3db8ff',
    gem: { badgeId: 'web-caixa-perfeita', name: 'Caixa Perfeita', icon: 'box', sides: 4, c1: '#9be3ff', c2: '#0e7490', tier: 'comum' },
    piece: 'cards',
    pieceName: 'cards de projeto',
    say: ['Pro CSS, tudo é caixa: conteúdo, padding, borda e margem.', 'Ajuste até ficar igual ao alvo.'],
    doc: { label: 'MDN · box model', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Styling_basics/Box_model' },
    rounds: [
      {
        type: 'sort',
        title: 'Camadas da caixa',
        sub: 'Toque na camada certa.',
        time: 28,
        maxErr: 3,
        buckets: [
          { id: 'c', label: 'content', tone: 'js' },
          { id: 'p', label: 'padding', tone: 'neon' },
          { id: 'b', label: 'border', tone: 'html' },
          { id: 'm', label: 'margin', tone: 'css' },
        ],
        items: [
          ['o texto do card', 'c'],
          ['espaço DENTRO da borda', 'p'],
          ['a linha em volta', 'b'],
          ['espaço FORA da borda', 'm'],
          ['respiro entre dois cards', 'm'],
          ['distância do texto até a borda', 'p'],
        ],
      },
      {
        type: 'tune',
        title: 'Copie o card',
        sub: 'Deixe igual ao alvo.',
        mode: 'box',
        ctrls: [
          { p: 'padding', o: ['0px', '8px', '16px', '28px'] },
          { p: 'border-width', o: ['0px', '2px', '6px'] },
          { p: 'border-radius', o: ['0px', '8px', '20px'] },
        ],
        target: { padding: '28px', 'border-width': '2px', 'border-radius': '20px' },
      },
      {
        type: 'fill',
        lang: 'css',
        title: 'Card de projeto',
        sub: 'Qual valor de padding funciona?',
        html: '<div class="card">Meu projeto</div>',
        pre: '.card {\n  border: 2px solid #3db8ff;\n  padding: ',
        options: ['20px', '20', 'vinte'],
        answer: '20px',
        post: ';\n  border-radius: 12px;\n}',
      },
    ],
  },
  {
    id: 'w8',
    title: 'Flexbox',
    year: '2009+',
    color: '#3db8ff',
    gem: { badgeId: 'web-mestre-flex', name: 'Mestre do Flex', icon: 'flex', sides: 8, c1: '#7cc7ff', c2: '#4338ca', tier: 'comum' },
    piece: 'flex',
    pieceName: 'projetos lado a lado',
    say: ['Flexbox alinha caixas em linha ou coluna.', 'Mova as peças até o alvo!'],
    doc: { label: 'MDN · flexbox', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/CSS_layout/Flexbox' },
    rounds: [
      {
        type: 'tune',
        title: 'Arena Flex 1',
        sub: 'Leve os blocos até as marcas.',
        mode: 'flex',
        ctrls: [{ p: 'justify-content', o: ['flex-start', 'center', 'flex-end', 'space-between'] }],
        target: { 'justify-content': 'flex-end' },
      },
      {
        type: 'tune',
        title: 'Arena Flex 2',
        sub: 'Agora em dois eixos.',
        mode: 'flex',
        ctrls: [
          { p: 'justify-content', o: ['flex-start', 'center', 'space-between', 'space-around'] },
          { p: 'align-items', o: ['flex-start', 'center', 'flex-end'] },
        ],
        target: { 'justify-content': 'space-around', 'align-items': 'center' },
      },
      {
        type: 'tune',
        title: 'Arena Flex 3',
        sub: 'Virou coluna!',
        mode: 'flex',
        ctrls: [
          { p: 'flex-direction', o: ['row', 'column'] },
          { p: 'justify-content', o: ['flex-start', 'center', 'flex-end'] },
          { p: 'align-items', o: ['flex-start', 'center', 'flex-end'] },
        ],
        target: { 'flex-direction': 'column', 'justify-content': 'center', 'align-items': 'flex-end' },
      },
      {
        type: 'fill',
        lang: 'css',
        title: 'Projetos lado a lado',
        sub: 'Qual display põe lado a lado?',
        html: BASE_CARDS,
        pre: '.grade {\n  display: ',
        options: ['flex', 'flexbox', 'lado-a-lado'],
        answer: 'flex',
        post: ';\n  gap: 12px;\n}\n.projeto, .outro { padding: 16px; background: #e0f2fe; }',
      },
    ],
  },
  {
    id: 'w9',
    title: 'Variáveis e Eventos',
    year: '1995 · JS',
    color: '#ffe14d',
    gem: { badgeId: 'web-raio-eich', name: 'Raio de Eich', icon: 'bolt', sides: 6, c1: '#fff08a', c2: '#ca8a04', tier: 'comum' },
    piece: 'greet',
    pieceName: 'saudação viva',
    say: ['1995: Brendan Eich cria o JavaScript em uns 10 dias.', 'Agora a página ganha vida!'],
    doc: { label: 'MDN · eventos', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Scripting/Events' },
    rounds: [
      {
        type: 'sort',
        title: 'Qual o tipo?',
        sub: 'Toque rápido!',
        time: 25,
        maxErr: 3,
        buckets: [
          { id: 's', label: 'string', s: 'texto', tone: 'neon' },
          { id: 'n', label: 'number', s: 'número', tone: 'css' },
          { id: 'b', label: 'boolean', s: 'sim/não', tone: 'pink' },
        ],
        items: [
          ['"Ana"', 's'],
          ['42', 'n'],
          ['true', 'b'],
          ['"42"', 's'],
          ['3.14', 'n'],
          ['false', 'b'],
          ["'oi'", 's'],
          ['-7', 'n'],
        ],
      },
      {
        type: 'order',
        title: 'Pegue o botão',
        sub: 'Monte a linha de JS.',
        tokens: ['const', 'botao', '=', 'document.querySelector("button")', ';'],
        extra: ['var=', 'querySelector'],
      },
      {
        type: 'quiz',
        title: 'Interrogatório da AVT',
        sub: 'Errou? Perde uma vida.',
        time: 25,
        code: 'let x = "1" + 1;\nconsole.log(x);',
        options: ['11', '2', '"1"1'],
        answer: '11',
      },
      {
        type: 'blocks',
        lang: 'js',
        title: 'Contador de cliques',
        sub: 'Monte o que o clique faz. Depois, teste!',
        block: true,
        joiner: '\n',
        html: '<button>Curtir</button> <span id="n">0</span>',
        pre: 'const botao = document.querySelector("button");\nconst n = document.querySelector("#n");\nlet cliques = 0;\nbotao.addEventListener("click", () => {\n',
        tokens: ['  cliques++;', '  n.textContent = cliques;'],
        extra: ['  cliques--;'],
        post: '\n});',
      },
    ],
  },
  {
    id: 'w10',
    title: 'DOM Vivo',
    year: '1998 · DOM',
    color: '#ffe14d',
    gem: { badgeId: 'web-raiz-dom', name: 'Raiz do DOM', icon: 'tree', sides: 10, c1: '#ffe98a', c2: '#a16207', tier: 'comum' },
    piece: 'dark',
    pieceName: 'modo escuro',
    say: ['O DOM é a árvore da página.', 'O JS mexe nela ao vivo. Último passo!'],
    doc: {
      label: 'MDN · manipulando o DOM',
      url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Scripting/DOM_scripting',
    },
    rounds: [
      {
        type: 'defuse',
        title: 'Desarme a variante',
        sub: 'Toque na linha com bug antes do reset!',
        time: 20,
        maxErr: 2,
        timeout: 'Reset! A variante escapou.',
        lines: ['const titulo = document.querySelector("#titulo");', 'titulo.textContent = "Oi!";', 'document.querySelecter("p");', 'const x = 5;'],
        bad: 2,
        why: 'querySelector com “o”',
      },
      {
        type: 'blocks',
        lang: 'js',
        title: 'Troque o título',
        sub: 'Monte a linha: o #titulo vira seu nome.',
        html: '<h1 id="titulo">Carregando...</h1>',
        pre: 'const titulo = document.querySelector("#titulo");\n',
        tokens: ['titulo', '.textContent', ' = ', '"{NAME}"', ';'],
        extra: ['.textContnet', ' == '],
      },
      {
        type: 'blocks',
        lang: 'js',
        title: 'Modo escuro',
        sub: 'Monte o clique. Depois, toque em Tema!',
        html: `${DARK_HTML}<p>Meu portfólio</p>`,
        pre: 'const tema = document.querySelector("#tema");\ntema.addEventListener("click", () => {\n  ',
        tokens: ['document.body', '.classList', '.toggle(', '"escuro"', ');'],
        extra: ['.add(', '.style'],
        post: '\n});',
      },
    ],
  },
];

/** O chefe da era: o Eco, a variante do próprio viajante. */
export const ecoBoss: WebBoss = {
  id: 'eco',
  name: 'Eco',
  face: 'E C O',
  say: ['O Eco chegou e apagou seu portfólio!', 'Sem perder vida, a insígnia lendária é sua.'],
  rounds: [
    { type: 'catch', title: 'Fragmentos do Eco', sub: 'Pegue só tags reais. Rápido!', time: 18, need: 9, maxErr: 2, good: TAGS_HTML, bad: [...TAGS_FAKE, '404', '<null>'] },
    {
      type: 'portal',
      title: 'Portal instável',
      sub: 'Reerga o esqueleto antes do portal fechar!',
      block: true,
      time: 40,
      tokens: ['<!DOCTYPE html>', '<html>', '<head>', '<link rel="stylesheet" href="style.css">', '</head>', '<body>', '<script src="script.js"></script>', '</body>', '</html>'],
    },
    {
      type: 'bug',
      title: 'Código corrompido',
      sub: '4 bugs, 3 linguagens.',
      time: 30,
      lines: [
        '<img src="eu.jpg">',
        'h1 { color: tomato }',
        '.card { padding 12px; }',
        '<a href="#contato">Contato</a>',
        'botao.addEventListener("click", abrir);',
        'document.querySelectorAll(".card").forEach(c => c.remove();',
        '<p>Olá<p>',
      ],
      bad: [0, 2, 5, 6],
    },
    {
      type: 'tune',
      title: 'Realinhe os projetos',
      sub: 'Encaixe no alvo.',
      mode: 'flex',
      time: 30,
      ctrls: [
        { p: 'flex-direction', o: ['row', 'column'] },
        { p: 'justify-content', o: ['flex-start', 'center', 'space-between'] },
        { p: 'align-items', o: ['flex-start', 'center', 'flex-end'] },
      ],
      target: { 'flex-direction': 'row', 'justify-content': 'space-between', 'align-items': 'flex-end' },
    },
    {
      type: 'sort',
      title: 'Separe o caos',
      sub: 'HTML, CSS ou JS?',
      time: 22,
      maxErr: 2,
      buckets: [
        { id: 'h', label: 'HTML', tone: 'html' },
        { id: 'c', label: 'CSS', tone: 'css' },
        { id: 'j', label: 'JS', tone: 'js' },
      ],
      items: [
        ['<section>', 'h'],
        ['display: flex', 'c'],
        ['addEventListener', 'j'],
        ['<nav>', 'h'],
        ['border-radius', 'c'],
        ['const', 'j'],
        ['alt="foto"', 'h'],
        [':hover', 'c'],
        ['classList.toggle', 'j'],
      ],
    },
    {
      type: 'quiz',
      title: 'Interrogatório da AVT',
      sub: 'O Eco quer saber. Errou, perde vida!',
      time: 20,
      code: 'const tags = ["h1", "p"];\nconsole.log(tags.length);',
      options: ['2', '1', '"h1p"'],
      answer: '2',
    },
    {
      type: 'blocks',
      lang: 'js',
      title: 'Golpe final',
      sub: 'Monte o clique que acende o modo escuro!',
      html: `${DARK_HTML}<p>O Eco não passará</p>`,
      pre: 'const tema = document.querySelector("#tema");\ntema.addEventListener(',
      tokens: ['"click"', ', () => ', 'document.body.classList.toggle("escuro")', ');'],
      extra: ['"clik"', 'document.body.classList.add("escuro")'],
    },
  ],
};

/** Insígnias especiais do Eco: rara (venceu) e lendária (venceu sem perder coração). */
export const webSpecialGems: { rara: GemSpec; lendaria: GemSpec } = {
  rara: { badgeId: 'web-guardiao-portfolio', name: 'Guardião do Portfólio', icon: 'portfolio', sides: 8, c1: '#ffb0f2', c2: '#6d28d9', tier: 'rara' },
  lendaria: { badgeId: 'web-tecelao-www', name: 'Tecelão da World Wide Web', icon: 'www', sides: 12, c1: '#fff3b0', c2: '#b45309', tier: 'lendaria' },
};
