import type { WebMoon } from '@/domain/webEra';
import { BASE_CARDS } from './era';

/**
 * As 3 luas que nascem da vitória sobre o Eco (protótipo: `MOONS`). Cada uma tem 5 trilhas,
 * um chefe e uma insígnia exclusiva. Elas orbitam o portal da Era da Web no mapa principal.
 */
export const webMoons: WebMoon[] = [
  {
    id: 'mh',
    name: 'Lua HTML',
    short: 'HTML',
    color: '#ff7a3d',
    description: 'Formulários, tabelas, mídia, acessibilidade e SEO, e o chefe O Silenciador, que apaga o significado das tags.',
    boss: {
      id: 'mh-chefe',
      name: 'O Silenciador',
      face: '< />',
      say: ['O Silenciador apaga o significado das tags.', 'Leitores de tela ficaram mudos!'],
      rounds: [
        {
          type: 'defuse',
          title: 'Desarme o Silenciador',
          sub: 'Ache a tag sem significado antes do reset!',
          time: 16,
          maxErr: 2,
          timeout: 'Reset! O Silenciador venceu essa.',
          lines: ['<header>', '<nav>', '<div onclick="abrir()">Menu</div>', '<main>', '<footer>'],
          bad: 2,
          why: 'div clicável: use <button>',
        },
        {
          type: 'bug',
          title: 'Significado roubado',
          sub: 'Ache as 3 falhas.',
          time: 22,
          lines: ['<div class="menu">', '<nav>', '<img src="eu.png">', '<h1>Ana</h1>', '<input type="mail">'],
          bad: [0, 2, 4],
        },
        {
          type: 'blocks',
          lang: 'html',
          title: 'Devolva a voz',
          sub: 'Monte o form com o rótulo ligado ao campo.',
          block: true,
          pre: '<form>\n',
          tokens: ['<label for="email">', 'E-mail', '</label>', '<input type="email" id="email">'],
          extra: ['<input type="mail">', '<label>'],
          post: '\n</form>',
        },
        {
          type: 'catch',
          title: 'Última onda',
          sub: 'Só semânticas!',
          time: 18,
          need: 8,
          maxErr: 2,
          good: ['<header>', '<nav>', '<main>', '<article>', '<footer>', '<label>', '<figure>', '<table>'],
          bad: ['<div>', '<span>', '<font>', '<center>', '<b>'],
        },
      ],
    },
    gem: { badgeId: 'web-coroa-marcacao', name: 'Coroa da Marcação', icon: 'crown', sides: 8, c1: '#ffb38a', c2: '#9a3412', tier: 'lua' },
    trails: [
      {
        id: 'mh1',
        title: 'Formulários',
        icon: 'form',
        say: ['Formulário é como o site escuta o visitante.'],
        doc: { label: 'MDN · Formulários', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Extensions/Forms/Your_first_form' },
        rounds: [
          {
            type: 'catch',
            title: 'Tipos de <input>',
            sub: 'Pegue os type que existem.',
            time: 22,
            need: 7,
            maxErr: 3,
            good: ['email', 'password', 'number', 'date', 'checkbox', 'radio', 'color', 'range'],
            bad: ['mail', 'senha', 'numero', 'texto', 'clique'],
          },
          {
            type: 'blocks',
            lang: 'html',
            title: 'Form de contato',
            sub: 'Monte o form de cima pra baixo.',
            block: true,
            tokens: ['<form>', '<input type="email" placeholder="seu@email.com">', '<button>Enviar</button>', '</form>'],
            extra: ['<input type="mail">'],
          },
        ],
      },
      {
        id: 'mh2',
        title: 'Tabelas',
        icon: 'table',
        say: ['Tabela é para dados em linhas e colunas. Não para layout!'],
        doc: { label: 'MDN · Tabelas', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/HTML_table_basics' },
        rounds: [
          {
            type: 'order',
            title: 'Monte a tabela',
            sub: 'Uma linha com cabeçalho.',
            preview: true,
            block: true,
            tokens: ['<table>', '<tr>', '<th>Projeto</th>', '<th>Ano</th>', '</tr>', '<tr>', '<td>Portfólio</td>', '<td>2026</td>', '</tr>', '</table>'],
          },
          {
            type: 'sort',
            title: 'Peças da tabela',
            sub: 'Toque rápido.',
            time: 22,
            maxErr: 2,
            buckets: [
              { id: 'tr', label: '<tr>', tone: 'html' },
              { id: 'th', label: '<th>', tone: 'js' },
              { id: 'td', label: '<td>', tone: 'css' },
            ],
            items: [
              ['uma linha inteira', 'tr'],
              ['título da coluna', 'th'],
              ['um dado comum', 'td'],
              ['“Nome”, no topo', 'th'],
              ['o valor “2026”', 'td'],
              ['agrupa células lado a lado', 'tr'],
            ],
          },
        ],
      },
      {
        id: 'mh3',
        title: 'Listas e Mídia',
        icon: 'play',
        say: ['Listas organizam, vídeo e áudio dão vida.'],
        doc: { label: 'MDN · Listas e Mídia', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio' },
        rounds: [
          {
            type: 'blocks',
            lang: 'html',
            title: 'Lista de skills',
            sub: 'Monte o <ul>: HTML, CSS, JS.',
            block: true,
            tokens: ['<ul>', '<li>HTML</li>', '<li>CSS</li>', '<li>JS</li>', '</ul>'],
            extra: ['<p>JS</p>'],
          },
          {
            type: 'bug',
            title: 'Mídia quebrada',
            sub: 'Toque nos 2 erros.',
            time: 25,
            lines: ['<video src="demo.mp4" controls></video>', '<audio scr="tema.mp3" controls></audio>', '<ol><li>Primeiro</li></ol>', '<ul><p>Item</p></ul>'],
            bad: [1, 3],
            why: ['', 'é src, não scr', '', 'dentro de <ul> vai <li>'],
          },
        ],
      },
      {
        id: 'mh4',
        title: 'Acessibilidade',
        icon: 'a11y',
        say: ['Site bom é site que todo mundo consegue usar.'],
        doc: { label: 'MDN · Acessibilidade', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Accessibility/HTML' },
        rounds: [
          {
            type: 'bug',
            title: 'Barreiras',
            sub: 'Toque nas 3 barreiras.',
            time: 28,
            lines: ['<img src="foto.jpg">', '<button>Enviar</button>', '<button></button>', '<label for="email">E-mail</label>', '<div onclick="abrir()">Menu</div>'],
            bad: [0, 2, 4],
            why: ['falta alt', '', 'botão sem texto', '', 'use <button>, não div clicável'],
          },
          {
            type: 'fill',
            lang: 'html',
            title: 'Rótulo ligado',
            sub: 'O que liga o input ao label?',
            pre: '<label for="nome">Nome</label>\n<input ',
            options: ['id', 'for', 'label'],
            answer: 'id',
            post: '="nome">',
          },
        ],
      },
      {
        id: 'mh5',
        title: 'Meta e SEO',
        icon: 'meta',
        say: ['As metas do <head> apresentam seu site ao Google.'],
        doc: { label: 'MDN · Meta e SEO', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Structuring_content/Webpage_metadata' },
        rounds: [
          {
            type: 'order',
            title: 'Head turbinado',
            sub: 'Na ordem.',
            block: true,
            tokens: ['<head>', '<meta charset="utf-8">', '<meta name="viewport" content="width=device-width">', '<meta name="description" content="Portfólio de Ana">', '<title>Ana · Dev</title>', '</head>'],
          },
          {
            type: 'catch',
            title: 'Metas reais',
            sub: 'Pegue os name de meta válidos.',
            time: 20,
            need: 6,
            maxErr: 3,
            good: ['description', 'viewport', 'author', 'keywords', 'theme-color', 'robots'],
            bad: ['descricao', 'tela', 'dono', 'cor', 'google'],
          },
        ],
      },
    ],
  },
  {
    id: 'mc',
    name: 'Lua CSS',
    short: 'CSS',
    color: '#3db8ff',
    description: 'Grid, responsivo, variáveis, animações e posicionamento, e o chefe Glitch Cromático, que bagunça cores e layouts.',
    boss: {
      id: 'mc-chefe',
      name: 'Glitch Cromático',
      face: '#!?',
      say: ['O Glitch Cromático bagunçou cores e layouts da Web!'],
      rounds: [
        {
          type: 'tune',
          title: 'Recalibrar grid',
          sub: 'Rápido!',
          mode: 'grid',
          time: 25,
          ctrls: [
            { p: 'grid-template-columns', o: ['1fr', '1fr 1fr', '1fr 1fr 1fr', '2fr 1fr'] },
            { p: 'gap', o: ['0px', '6px', '16px'] },
          ],
          target: { 'grid-template-columns': '1fr 1fr 1fr', gap: '6px' },
        },
        {
          type: 'portal',
          title: 'Portal instável',
          sub: 'Monte a regra antes do portal fechar!',
          block: true,
          time: 22,
          tokens: ['.grade {', '  display: grid;', '  grid-template-columns: 1fr 1fr;', '}'],
          extra: ['  display: grade;'],
        },
        {
          type: 'bug',
          title: 'CSS corrompido',
          sub: '3 bugs.',
          time: 22,
          lines: ['h1 { color: var(--cor) }', '.card { paddin: 10px; }', '@media (max-width: 600px) { }', '.btn { transition: .3s }', 'p { color: red', '.a { position: absolut; }'],
          bad: [1, 4, 5],
        },
        {
          type: 'blocks',
          lang: 'css',
          title: 'Golpe cromático',
          sub: 'Crie a variável --c e pinte o fundo com ela.',
          block: true,
          html: '<p>Cor restaurada</p>',
          tokens: [':root {', '  --c: #0ea5e9;', '}', 'body { background: var(--c); }'],
          extra: ['body { background: --c; }', '  $c: #0ea5e9;'],
        },
      ],
    },
    gem: { badgeId: 'web-prisma-cascata', name: 'Prisma Cascata', icon: 'prism', sides: 8, c1: '#9be3ff', c2: '#1e3a8a', tier: 'lua' },
    trails: [
      {
        id: 'mc1',
        title: 'Grid',
        icon: 'grid',
        say: ['Grid é layout em linhas E colunas ao mesmo tempo.'],
        doc: { label: 'MDN · Grid', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/CSS_layout/Grids' },
        rounds: [
          {
            type: 'tune',
            title: 'Arena Grid',
            sub: 'Igual ao alvo.',
            mode: 'grid',
            ctrls: [
              { p: 'grid-template-columns', o: ['1fr', '1fr 1fr', '1fr 1fr 1fr', '2fr 1fr'] },
              { p: 'gap', o: ['0px', '6px', '16px'] },
            ],
            target: { 'grid-template-columns': '2fr 1fr', gap: '16px' },
          },
          {
            type: 'fill',
            lang: 'css',
            title: 'Galeria',
            sub: '3 colunas iguais. Qual valor?',
            html: BASE_CARDS,
            pre: '.grade {\n  display: grid;\n  grid-template-columns: ',
            options: ['repeat(3, 1fr)', '3 colunas', '1fr, 1fr, 1fr'],
            answer: 'repeat(3, 1fr)',
            post: ';\n  gap: 8px;\n}',
          },
        ],
      },
      {
        id: 'mc2',
        title: 'Responsivo',
        icon: 'phone',
        say: ['A maioria abre seu site no celular. Media query adapta.'],
        doc: { label: 'MDN · Responsivo', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/CSS_layout/Media_queries' },
        rounds: [
          {
            type: 'order',
            title: 'Monte a media query',
            sub: 'Celular empilha os cards.',
            tokens: ['@media', '(max-width: 600px)', '{', ' .grade { flex-direction: column; }', '}'],
          },
          {
            type: 'fill',
            lang: 'css',
            title: 'Tela de celular',
            sub: 'A prévia tem 360px. Qual condição empilha?',
            narrow: true,
            html: BASE_CARDS,
            pre: '.grade { display: flex; gap: 8px; }\n@media (',
            options: ['max-width: 600px', 'min-width: 900px', 'tela: celular'],
            answer: 'max-width: 600px',
            post: ') {\n  .grade { flex-direction: column; }\n}',
          },
        ],
      },
      {
        id: 'mc3',
        title: 'Variáveis CSS',
        icon: 'vars',
        say: ['Defina a cor uma vez, use em todo lugar.'],
        doc: { label: 'MDN · Variáveis CSS', url: 'https://developer.mozilla.org/pt-BR/docs/Web/CSS/Using_CSS_custom_properties' },
        rounds: [
          {
            type: 'catch',
            title: 'Uso correto',
            sub: 'Pegue só sintaxe válida.',
            time: 20,
            need: 6,
            maxErr: 3,
            good: ['--cor: #f0f', 'var(--cor)', '--espaco: 8px', 'var(--espaco)', ':root', '--fonte: serif'],
            bad: ['$cor', 'var(cor)', '-cor: red', '@cor', 'var[--cor]'],
          },
          {
            type: 'fill',
            lang: 'css',
            title: 'Tema com variável',
            sub: 'Use a variável no h1.',
            html: '<h1>Ana</h1>',
            pre: ':root { --destaque: hotpink; }\nh1 { color: ',
            options: ['var(--destaque)', '--destaque', '$destaque'],
            answer: 'var(--destaque)',
            post: '; }',
          },
        ],
      },
      {
        id: 'mc4',
        title: 'Animações',
        icon: 'wave',
        say: ['Transição suaviza, animação dá vida.'],
        doc: { label: 'MDN · Animações', url: 'https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_animations/Using_CSS_animations' },
        rounds: [
          {
            type: 'order',
            title: 'Keyframes',
            sub: 'Monte a animação.',
            block: true,
            tokens: ['@keyframes pulo {', '  from { transform: translateY(0); }', '  to { transform: translateY(-10px); }', '}'],
          },
          {
            type: 'fill',
            lang: 'css',
            title: 'Botão suave',
            sub: 'Passe o mouse no botão depois!',
            html: '<button class="btn">Contrate-me</button>',
            pre: '.btn {\n  transition: ',
            options: ['transform .3s', '3 segundos', 'devagar'],
            answer: 'transform .3s',
            post: ';\n}\n.btn:hover { transform: scale(1.1); }',
          },
        ],
      },
      {
        id: 'mc5',
        title: 'Posicionamento',
        icon: 'pin',
        say: ['position tira a caixa do fluxo normal.'],
        doc: { label: 'MDN · Posicionamento', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/CSS_layout/Positioning' },
        rounds: [
          {
            type: 'tune',
            title: 'Selo no canto',
            sub: 'Leve o selo ao alvo.',
            mode: 'pos',
            ctrls: [
              { p: 'position', o: ['static', 'absolute'] },
              { p: 'top', o: ['0px', '40px', 'auto'] },
              { p: 'right', o: ['0px', '40px', 'auto'] },
            ],
            target: { position: 'absolute', top: '0px', right: '0px' },
          },
          {
            type: 'sort',
            title: 'Qual position?',
            sub: 'Toque rápido.',
            time: 22,
            maxErr: 2,
            buckets: [
              { id: 'r', label: 'relative', tone: 'css' },
              { id: 'a', label: 'absolute', tone: 'html' },
              { id: 'f', label: 'fixed', tone: 'js' },
              { id: 's', label: 'sticky', tone: 'neon' },
            ],
            items: [
              ['menu que fica preso ao rolar a seção', 's'],
              ['botão “voltar ao topo” sempre na tela', 'f'],
              ['selo no canto do card', 'a'],
              ['referência pro filho absolute', 'r'],
              ['chat flutuante', 'f'],
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'mj',
    name: 'Lua JS',
    short: 'JS',
    color: '#ffe14d',
    description: 'Arrays, funções, JSON, fetch e localStorage, e o chefe Loop Infinito, que prende o navegador girando para sempre.',
    boss: {
      id: 'mj-chefe',
      name: 'Loop Infinito',
      face: '∞',
      say: ['O Loop Infinito prende o navegador para sempre.', 'Só lógica limpa quebra o ciclo.'],
      rounds: [
        {
          type: 'bug',
          title: 'Ciclo infinito',
          sub: '3 bugs.',
          time: 22,
          lines: ['for (let i = 0; i < 3; i--) {}', 'const lista = [1, 2, 3];', 'while (true) {}', 'lista.forEach(n => console.log(n));', 'const x = JSON.parse("{nome:1}");'],
          bad: [0, 2, 4],
        },
        {
          type: 'quiz',
          title: 'Interrogatório da AVT',
          sub: 'Errou? Perde uma vida.',
          time: 18,
          code: 'const a = [1, 2, 3];\nconsole.log(a[0] + a[2]);',
          options: ['4', '13', '3'],
          answer: '4',
        },
        {
          type: 'portal',
          title: 'Portal instável',
          sub: 'Quebre o loop antes do portal fechar!',
          time: 22,
          tokens: ['for', '(let i = 0;', 'i < lista.length;', 'i++)', '{ total += lista[i] }'],
          extra: ['i--)'],
        },
        {
          type: 'fill',
          lang: 'js',
          title: 'Golpe final',
          sub: 'total([1, 2, 3]) precisa dar 6.',
          pre: 'function total(arr) {\n  return arr.reduce((a, b) => ',
          options: ['a + b', 'a * b', 'a - b'],
          answer: 'a + b',
          post: ', 0);\n}\nconsole.log(total([1, 2, 3]));',
        },
      ],
    },
    gem: { badgeId: 'web-motor-eventos', name: 'Motor de Eventos', icon: 'infinity', sides: 10, c1: '#fff08a', c2: '#854d0e', tier: 'lua' },
    trails: [
      {
        id: 'mj1',
        title: 'Arrays e Loops',
        icon: 'loop',
        say: ['Array guarda uma lista; loop passa por cada item.'],
        doc: { label: 'MDN · Arrays e Loops', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Scripting/Loops' },
        rounds: [
          { type: 'order', title: 'Monte o for', sub: 'Conte de 0 a 2.', tokens: ['for', '(let i = 0;', 'i < 3;', 'i++)', '{ console.log(i) }'] },
          {
            type: 'fill',
            lang: 'js',
            title: 'Lista de projetos',
            sub: 'O que vira um <li> por item?',
            html: '<ul id="lista"></ul>',
            pre: 'const projetos = ["Portfólio", "Calculadora", "To-do"];\nconst lista = document.querySelector("#lista");\nprojetos.forEach(p => {\n  lista.innerHTML += ',
            options: ['`<li>${p}</li>`', '<li>p</li>', 'p.li'],
            answer: '`<li>${p}</li>`',
            post: ';\n});',
          },
        ],
      },
      {
        id: 'mj2',
        title: 'Funções',
        icon: 'fn',
        say: ['Função é uma receita: entra algo, sai algo.'],
        doc: { label: 'MDN · Funções', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Scripting/Functions' },
        rounds: [
          {
            type: 'fill',
            lang: 'js',
            title: 'Função dobro',
            sub: 'dobro(4) precisa dar 8.',
            pre: 'function dobro(n) {\n  return ',
            options: ['n * 2', 'n ** 2', '2'],
            answer: 'n * 2',
            post: ';\n}\nconsole.log(dobro(4));',
          },
          {
            type: 'bug',
            title: 'Funções quebradas',
            sub: 'Toque nos 2 erros.',
            time: 22,
            lines: ['const soma = (a, b) => a + b;', 'function oi() { return "oi" }', 'const x = soma(2 3);', 'funtion tchau() {}'],
            bad: [2, 3],
          },
        ],
      },
      {
        id: 'mj3',
        title: 'Objetos e JSON',
        icon: 'obj',
        say: ['Objeto junta dados com nome. JSON é como eles viajam.'],
        doc: { label: 'MDN · Objetos e JSON', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Scripting/JSON' },
        rounds: [
          {
            type: 'catch',
            title: 'JSON válido',
            sub: 'Pegue só JSON certo.',
            time: 22,
            need: 6,
            maxErr: 3,
            good: ['{"nome":"Ana"}', '[1,2,3]', '{"ok":true}', '"texto"', '{"idade":20}', 'null'],
            bad: ["{nome:'Ana'}", "{'a':1}", '[1,2,]', '{ok:true}', 'undefined'],
          },
          {
            type: 'fill',
            lang: 'js',
            title: 'Seu perfil',
            sub: 'skills é uma lista. Qual valor?',
            pre: 'const perfil = {\n  nome: "Ana",\n  skills: ',
            options: ['["HTML", "CSS"]', '"HTML", "CSS"', '{HTML, CSS}'],
            answer: '["HTML", "CSS"]',
            post: '\n};\nconsole.log(perfil.skills.length);',
          },
        ],
      },
      {
        id: 'mj4',
        title: 'Fetch e Async',
        icon: 'cloud',
        say: ['fetch busca dados de outro lugar. await espera chegar.'],
        doc: { label: 'MDN · Fetch e Async', url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development/Core/Scripting/Network_requests' },
        rounds: [
          {
            type: 'order',
            title: 'Monte a busca',
            sub: 'Na ordem.',
            block: true,
            tokens: ['async function carregar() {', '  const r = await fetch("/api/projetos");', '  const dados = await r.json();', '  console.log(dados);', '}'],
          },
          {
            type: 'bug',
            title: 'Promessas quebradas',
            sub: 'Toque nos 2 erros.',
            time: 22,
            lines: ['const r = fetch(url);', 'const r = await fetch(url);', 'const d = r.json;', 'const d = await r.json();'],
            bad: [0, 2],
            why: ['faltou await', '', 'json é função: r.json()', ''],
          },
        ],
      },
      {
        id: 'mj5',
        title: 'Memória Local',
        icon: 'disk',
        say: ['localStorage guarda dados no navegador, mesmo fechando a aba.'],
        doc: { label: 'MDN · localStorage', url: 'https://developer.mozilla.org/pt-BR/docs/Web/API/Window/localStorage' },
        rounds: [
          { type: 'order', title: 'Salvar o tema', sub: 'Monte a linha.', tokens: ['localStorage', '.setItem(', '"tema",', '"escuro"', ')'] },
          {
            type: 'sort',
            title: 'Salvar ou ler?',
            sub: 'Toque rápido.',
            time: 20,
            maxErr: 2,
            buckets: [
              { id: 's', label: 'setItem', s: 'salvar', tone: 'js' },
              { id: 'g', label: 'getItem', s: 'ler', tone: 'css' },
              { id: 'r', label: 'removeItem', s: 'apagar', tone: 'bad' },
            ],
            items: [
              ['guardar o nome do jogador', 's'],
              ['saber o tema ao abrir', 'g'],
              ['sair da conta', 'r'],
              ['lembrar a pontuação', 's'],
              ['mostrar recorde salvo', 'g'],
            ],
          },
        ],
      },
    ],
  },
];
