import type { Mission } from '@/domain/trail/types';

/**
 * As 12 missões práticas do laboratório, migradas de
 * legacy/Trilha_PostgreSQL_com_Laboratorio.html sem alteração de enunciado ou verificação.
 */
export const bancoDeDadosMissions: Mission[] = [
  {
    id: "m1",
    title: "Só o que tem estoque",
    ds: "loja",
    kind: 'select',
    ordered: true,
    brief: "Liste o <code>nome</code> e o <code>preco</code> dos produtos com estoque maior que zero, do mais barato para o mais caro.",
    hint: "Use WHERE para filtrar o estoque e ORDER BY para ordenar.",
    solution: "SELECT nome, preco FROM produtos WHERE estoque > 0 ORDER BY preco",
  },
  {
    id: "m2",
    title: "Caçando teclados",
    ds: "loja",
    kind: 'select',
    brief: "Mostre só a coluna <code>nome</code> dos produtos cujo nome começa com \"Teclado\".",
    hint: "LIKE com o coringa % depois da palavra.",
    solution: "SELECT nome FROM produtos WHERE nome LIKE 'Teclado%'",
  },
  {
    id: "m3",
    title: "Construa a tabela alunos",
    ds: "vazio",
    kind: 'state',
    brief: "No banco vazio, crie a tabela <code>alunos</code> com: <code>id</code> (SERIAL, chave primária), <code>nome</code> (VARCHAR(80), obrigatório) e <code>xp</code> (INTEGER, com valor padrão 0).",
    hint: "Veja o módulo 6. Lembre de PRIMARY KEY, NOT NULL e DEFAULT.",
    verify: "SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'alunos' ORDER BY ordinal_position",
    expect: [["id","integer","NO"],["nome","character varying","NO"],["xp","integer","YES"]],
  },
  {
    id: "m4",
    title: "Vendeu um mouse",
    ds: "loja",
    kind: 'state',
    brief: "Diminua em 1 o estoque do produto \"Mouse Gamer\". Cuidado: só ele pode mudar!",
    hint: "UPDATE ... SET estoque = estoque - 1 WHERE ... Sem WHERE você altera todos.",
    verify: "SELECT nome, estoque FROM produtos ORDER BY id",
    expect: [["Teclado Mecânico","15"],["Mouse Gamer","39"],["Monitor 24 pol","8"],["Teclado Compacto","0"]],
  },
  {
    id: "m5",
    title: "Nova categoria",
    ds: "loja",
    kind: 'state',
    brief: "Cadastre a categoria \"Headsets\" na tabela <code>categorias</code>.",
    hint: "INSERT INTO categorias (nome) VALUES (...). O id se preenche sozinho.",
    verify: "SELECT nome FROM categorias ORDER BY id",
    expect: [["Teclados"],["Mouses"],["Monitores"],["Headsets"]],
  },
  {
    id: "m6",
    title: "Quem comprou o quê",
    ds: "loja",
    kind: 'select',
    ordered: true,
    brief: "Liste o <code>nome</code> do cliente e o <code>total</code> de cada pedido (só clientes que têm pedido), ordenado pelo id do pedido.",
    hint: "INNER JOIN entre clientes e pedidos usando cliente_id = id.",
    solution: "SELECT c.nome, p.total FROM clientes c INNER JOIN pedidos p ON p.cliente_id = c.id ORDER BY p.id",
  },
  {
    id: "m7",
    title: "Produtos por categoria",
    ds: "loja",
    kind: 'select',
    brief: "Mostre o nome de cada categoria e quantos produtos ela tem, inclusive categorias sem produtos.",
    hint: "LEFT JOIN de categorias para produtos, COUNT(p.id) e GROUP BY.",
    solution: "SELECT c.nome, COUNT(p.id) FROM categorias c LEFT JOIN produtos p ON p.categoria_id = c.id GROUP BY c.nome",
  },
  {
    id: "m8",
    title: "Clientes de peso",
    ds: "loja",
    kind: 'select',
    brief: "Mostre o nome e o total gasto (soma dos pedidos) dos clientes que gastaram mais de 200.",
    hint: "JOIN, SUM, GROUP BY e o filtro do total vai no HAVING.",
    solution: "SELECT c.nome, SUM(p.total) FROM clientes c JOIN pedidos p ON p.cliente_id = c.id GROUP BY c.nome HAVING SUM(p.total) > 200",
  },
  {
    id: "m9",
    title: "Quem nunca comprou",
    ds: "loja",
    kind: 'select',
    brief: "Liste o <code>nome</code> dos clientes que não fizeram nenhum pedido. Use EXCEPT, NOT EXISTS ou LEFT JOIN.",
    hint: "Compare os ids de clientes com os cliente_id de pedidos.",
    solution: "SELECT nome FROM clientes WHERE id NOT IN (SELECT cliente_id FROM pedidos)",
  },
  {
    id: "m10",
    title: "Acima da média",
    ds: "loja",
    kind: 'select',
    brief: "Mostre o <code>nome</code> dos produtos com preço acima da média de todos os preços (subconsulta).",
    hint: "WHERE preco > (SELECT AVG(preco) FROM produtos).",
    solution: "SELECT nome FROM produtos WHERE preco > (SELECT AVG(preco) FROM produtos)",
  },
  {
    id: "m11",
    title: "Crie uma view",
    ds: "loja",
    kind: 'state',
    brief: "Crie a view <code>v_estoque_baixo</code> com o <code>nome</code> dos produtos com estoque menor que 10.",
    hint: "CREATE VIEW nome AS SELECT ... WHERE estoque < 10.",
    verify: "SELECT nome FROM v_estoque_baixo ORDER BY nome",
    expect: [["Monitor 24 pol"],["Teclado Compacto"]],
  },
  {
    id: "m12",
    title: "Acelere a busca",
    ds: "loja",
    kind: 'state',
    brief: "Crie um índice chamado <code>idx_clientes_nome</code> na coluna <code>nome</code> da tabela <code>clientes</code>.",
    hint: "CREATE INDEX nome ON tabela (coluna).",
    verify: "SELECT indexname FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_clientes_nome'",
    expect: [["idx_clientes_nome"]],
  },
];
