import type { Module } from '@/domain/trail/types';

/** Farol 3 da Lua de Java: operadores, condições e a armadilha == vs .equals(). */
export const modOperadores: Module = {
  id: 'operadores-condicoes-java',
  short: 'Comparar direito',
  title: 'Operadores, condições e a armadilha do ==',
  lead: 'Aqui mora um dos erros mais famosos entre quem começa em Java: comparar texto com o operador errado.',
  level: 'Base',
  blocks: [
    { t: 'h', x: 'Operadores aritméticos e de comparação' },
    {
      t: 'table',
      cols: ['Operador', 'Significado'],
      rows: [
        ['+ - * /', 'soma, subtração, multiplicação, divisão'],
        ['%', 'resto da divisão'],
        ['== !=', 'igual, diferente'],
        ['&& || !', 'e, ou, negação (símbolos, diferente de Python)'],
      ],
    },
    { t: 'h', x: 'Divisão entre inteiros trunca, sem avisar' },
    {
      t: 'code',
      file: 'Divisao.java',
      lang: 'java',
      nolab: true,
      x: 'int resultado = 5 / 2;\nSystem.out.println(resultado);   // 2, não 2.5',
    },
    {
      t: 'note',
      k: 'Cuidado',
      x: 'Se pelo menos um dos dois números for double, o resultado tem casas decimais: 5.0 / 2 vale 2.5. Entre dois int, o resultado é sempre truncado para int.',
      warn: true,
    },
    { t: 'h', x: 'if / else if / else' },
    {
      t: 'code',
      file: 'Decisao.java',
      lang: 'java',
      nolab: true,
      x: 'int nota = 7;\n\nif (nota >= 9) {\n    System.out.println("Excelente");\n} else if (nota >= 6) {\n    System.out.println("Aprovado");\n} else {\n    System.out.println("Precisa estudar mais");\n}',
    },
    {
      t: 'out',
      file: 'Decisao.out',
      x: 'Aprovado',
    },
    { t: 'h', x: 'A armadilha clássica: == não compara o conteúdo de objetos' },
    {
      t: 'p',
      x: 'Para tipos primitivos (como int), <code>==</code> compara o valor, e funciona como esperado. Mas <code>String</code> é um tipo de <b>referência</b>: <code>==</code> compara se são <b>o mesmo objeto na memória</b>, não se o texto é igual.',
    },
    {
      t: 'code',
      file: 'ComparaTexto.java',
      lang: 'java',
      expectError: true,
      nolab: true,
      x: 'String a = new String("java");\nString b = new String("java");\n\nSystem.out.println(a == b);          // false! objetos diferentes\nSystem.out.println(a.equals(b));     // true — mesmo conteúdo',
    },
    {
      t: 'note',
      k: 'A regra de ouro',
      x: 'Para comparar o conteúdo de dois textos (ou de qualquer objeto), use sempre .equals(), nunca ==. == é só para tipos primitivos (int, double, boolean, char).',
      warn: true,
    },
    { t: 'h', x: 'switch: outro jeito de ramificar' },
    {
      t: 'code',
      file: 'Switch.java',
      lang: 'java',
      nolab: true,
      x: 'int dia = 3;\nswitch (dia) {\n    case 1:\n        System.out.println("Segunda");\n        break;\n    case 2:\n        System.out.println("Terça");\n        break;\n    default:\n        System.out.println("Outro dia");\n}',
    },
    {
      t: 'note',
      k: 'Não esqueça o break',
      x: 'Sem break, o switch "cai" para o próximo case e continua executando (fall-through) — um comportamento que confunde bastante quem vem de outras linguagens.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      kind: "output",
      q: "Os dois lados são int. O que aparece na tela (código dentro do main)?",
      lang: "java",
      code: "int a = 5;\nint b = 2;\nSystem.out.println(a / b);",
      options: ["2.5", "2", "3", "erro de compilação"],
      answer: 1,
      explain: "Divisão entre dois int descarta a parte decimal: 5 / 2 dá 2. Para ter 2.5, um dos lados precisa ser double.",
    },
    {
      id: 'q2',
      q: 'Por que a == b pode retornar false mesmo quando a e b são duas Strings com o mesmo texto?',
      options: [
        'Porque Strings não podem ser comparadas',
        'Porque == compara se são o mesmo objeto na memória, não o conteúdo',
        'Porque Java não tem o operador ==',
        'Isso nunca acontece em Java',
      ],
      answer: 1,
      explain: 'String é um tipo de referência: == compara identidade (mesmo objeto), não o conteúdo do texto.',
      hint: 'Pense na diferença entre "é o mesmo objeto" e "tem o mesmo conteúdo".',
    },
    {
      id: 'q3',
      q: "Complete para comparar o conteúdo das duas Strings:",
      fill: true,
      pre: "if (a.",
      post: "(b)) {",
      accept: ["equals"],
      wrong: ["compare", "same", "is"],
      placeholder: "?",
      explain: "<code>a.equals(b)</code> compara o texto. O <code>==</code> compara se são o mesmo objeto na memória.",
    },
    {
      id: 'q4',
      kind: "output",
      q: "Esqueceram o break no primeiro case. O que aparece na tela (código dentro do main)?",
      lang: "java",
      code: "int opcao = 1;\nswitch (opcao) {\n  case 1:\n    System.out.print(\"Um\");\n  case 2:\n    System.out.print(\"Dois\");\n    break;\n  case 3:\n    System.out.print(\"Três\");\n}",
      options: ["Um", "UmDois", "UmDoisTrês", "erro de compilação"],
      answer: 1,
      explain: "Sem break, a execução \"cai\" para o próximo case (fall-through): imprime Um e Dois, e para no break do case 2.",
    },
    {
      id: 'q5',
      q: 'Complete: os operadores lógicos e, ou e negação em Java são escritos com os símbolos &&, || e ___.',
      fill: true,
      pre: 'Os operadores lógicos e, ou e negação em Java são escritos com os símbolos &&, || e',
      post: '.',
      accept: ['!'],
      wrong: ['~', '?', '^'],
      placeholder: 'símbolo',
      explain: 'Java usa símbolos (&&, ||, !), diferente de Python, que escreve and, or, not por extenso.',
    },
  ],
};
